// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sharetoken/taskmarket/task.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TaskType represents the type of marketplace task
type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_OPEN        TaskType = 1
	TaskType_TASK_TYPE_AUCTION     TaskType = 2
)

var TaskType_name = map[int32]string{
	0: "TASK_TYPE_UNSPECIFIED",
	1: "TASK_TYPE_OPEN",
	2: "TASK_TYPE_AUCTION",
}

var TaskType_value = map[string]int32{
	"TASK_TYPE_UNSPECIFIED": 0,
	"TASK_TYPE_OPEN":        1,
	"TASK_TYPE_AUCTION":     2,
}

func (x TaskType) String() string {
	return proto.EnumName(TaskType_name, int32(x))
}

func (TaskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34eef7f9fdca6f38, []int{0}
}

// TaskStatus represents the status of a marketplace task
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_DRAFT       TaskStatus = 1
	TaskStatus_TASK_STATUS_OPEN        TaskStatus = 2
	TaskStatus_TASK_STATUS_ASSIGNED    TaskStatus = 3
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 4
	TaskStatus_TASK_STATUS_REVIEW      TaskStatus = 5
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 6
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 7
	TaskStatus_TASK_STATUS_DISPUTED    TaskStatus = 8
)

var TaskStatus_name = map[int32]string{
	0: "TASK_STATUS_UNSPECIFIED",
	1: "TASK_STATUS_DRAFT",
	2: "TASK_STATUS_OPEN",
	3: "TASK_STATUS_ASSIGNED",
	4: "TASK_STATUS_IN_PROGRESS",
	5: "TASK_STATUS_REVIEW",
	6: "TASK_STATUS_COMPLETED",
	7: "TASK_STATUS_CANCELLED",
	8: "TASK_STATUS_DISPUTED",
}

var TaskStatus_value = map[string]int32{
	"TASK_STATUS_UNSPECIFIED": 0,
	"TASK_STATUS_DRAFT":       1,
	"TASK_STATUS_OPEN":        2,
	"TASK_STATUS_ASSIGNED":    3,
	"TASK_STATUS_IN_PROGRESS": 4,
	"TASK_STATUS_REVIEW":      5,
	"TASK_STATUS_COMPLETED":   6,
	"TASK_STATUS_CANCELLED":   7,
	"TASK_STATUS_DISPUTED":    8,
}

func (x TaskStatus) String() string {
	return proto.EnumName(TaskStatus_name, int32(x))
}

func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34eef7f9fdca6f38, []int{1}
}

// TaskCategory represents task categories
type TaskCategory int32

const (
	TaskCategory_TASK_CATEGORY_UNSPECIFIED TaskCategory = 0
	TaskCategory_TASK_CATEGORY_DEVELOPMENT TaskCategory = 1
	TaskCategory_TASK_CATEGORY_DESIGN      TaskCategory = 2
	TaskCategory_TASK_CATEGORY_WRITING     TaskCategory = 3
	TaskCategory_TASK_CATEGORY_RESEARCH    TaskCategory = 4
	TaskCategory_TASK_CATEGORY_MARKETING   TaskCategory = 5
	TaskCategory_TASK_CATEGORY_CONSULTING  TaskCategory = 6
	TaskCategory_TASK_CATEGORY_OTHER       TaskCategory = 7
)

var TaskCategory_name = map[int32]string{
	0: "TASK_CATEGORY_UNSPECIFIED",
	1: "TASK_CATEGORY_DEVELOPMENT",
	2: "TASK_CATEGORY_DESIGN",
	3: "TASK_CATEGORY_WRITING",
	4: "TASK_CATEGORY_RESEARCH",
	5: "TASK_CATEGORY_MARKETING",
	6: "TASK_CATEGORY_CONSULTING",
	7: "TASK_CATEGORY_OTHER",
}

var TaskCategory_value = map[string]int32{
	"TASK_CATEGORY_UNSPECIFIED": 0,
	"TASK_CATEGORY_DEVELOPMENT": 1,
	"TASK_CATEGORY_DESIGN":      2,
	"TASK_CATEGORY_WRITING":     3,
	"TASK_CATEGORY_RESEARCH":    4,
	"TASK_CATEGORY_MARKETING":   5,
	"TASK_CATEGORY_CONSULTING":  6,
	"TASK_CATEGORY_OTHER":       7,
}

func (x TaskCategory) String() string {
	return proto.EnumName(TaskCategory_name, int32(x))
}

func (TaskCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34eef7f9fdca6f38, []int{2}
}

// MilestoneStatus represents milestone status
type MilestoneStatus int32

const (
	MilestoneStatus_MILESTONE_STATUS_UNSPECIFIED MilestoneStatus = 0
	MilestoneStatus_MILESTONE_STATUS_PENDING     MilestoneStatus = 1
	MilestoneStatus_MILESTONE_STATUS_ACTIVE      MilestoneStatus = 2
	MilestoneStatus_MILESTONE_STATUS_SUBMITTED   MilestoneStatus = 3
	MilestoneStatus_MILESTONE_STATUS_APPROVED    MilestoneStatus = 4
	MilestoneStatus_MILESTONE_STATUS_REJECTED    MilestoneStatus = 5
	MilestoneStatus_MILESTONE_STATUS_PAID        MilestoneStatus = 6
)

var MilestoneStatus_name = map[int32]string{
	0: "MILESTONE_STATUS_UNSPECIFIED",
	1: "MILESTONE_STATUS_PENDING",
	2: "MILESTONE_STATUS_ACTIVE",
	3: "MILESTONE_STATUS_SUBMITTED",
	4: "MILESTONE_STATUS_APPROVED",
	5: "MILESTONE_STATUS_REJECTED",
	6: "MILESTONE_STATUS_PAID",
}

var MilestoneStatus_value = map[string]int32{
	"MILESTONE_STATUS_UNSPECIFIED": 0,
	"MILESTONE_STATUS_PENDING":     1,
	"MILESTONE_STATUS_ACTIVE":      2,
	"MILESTONE_STATUS_SUBMITTED":   3,
	"MILESTONE_STATUS_APPROVED":    4,
	"MILESTONE_STATUS_REJECTED":    5,
	"MILESTONE_STATUS_PAID":        6,
}

func (x MilestoneStatus) String() string {
	return proto.EnumName(MilestoneStatus_name, int32(x))
}

func (MilestoneStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34eef7f9fdca6f38, []int{3}
}

// Task represents a marketplace task
type Task struct {
	// id is the unique task identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// title is the task title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// description is the task description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// requester_id is the address of the task requester
	RequesterId string `protobuf:"bytes,4,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	// worker_id is the address of the assigned worker (if any)
	WorkerId string `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// task_type is the task type (open or auction)
	TaskType TaskType `protobuf:"varint,6,opt,name=task_type,json=taskType,proto3,enum=sharetoken.taskmarket.TaskType" json:"task_type,omitempty"`
	// category is the task category
	Category TaskCategory `protobuf:"varint,7,opt,name=category,proto3,enum=sharetoken.taskmarket.TaskCategory" json:"category,omitempty"`
	// status is the current task status
	Status TaskStatus `protobuf:"varint,8,opt,name=status,proto3,enum=sharetoken.taskmarket.TaskStatus" json:"status,omitempty"`
	// budget is the task budget in STT
	Budget uint64 `protobuf:"varint,9,opt,name=budget,proto3" json:"budget,omitempty"`
	// currency is the currency symbol (e.g., "STT", "USDC")
	Currency string `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	// deadline is the Unix timestamp deadline
	Deadline int64 `protobuf:"varint,11,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// skills are the required skills
	Skills []string `protobuf:"bytes,12,rep,name=skills,proto3" json:"skills,omitempty"`
	// subtasks are the decomposed subtasks
	Subtasks []Subtask `protobuf:"bytes,13,rep,name=subtasks,proto3" json:"subtasks"`
	// milestones are the task milestones
	Milestones []Milestone `protobuf:"bytes,14,rep,name=milestones,proto3" json:"milestones"`
	// created_at is the Unix timestamp of creation
	CreatedAt int64 `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the Unix timestamp of last update
	UpdatedAt int64 `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// assigned_at is the Unix timestamp of assignment
	AssignedAt int64 `protobuf:"varint,17,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	// completed_at is the Unix timestamp of completion
	CompletedAt int64 `protobuf:"varint,18,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// view_count is the number of views
	ViewCount int32 `protobuf:"varint,19,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	// application_count is the number of applications
	ApplicationCount int32 `protobuf:"varint,20,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
	// bid_count is the number of bids
	BidCount int32 `protobuf:"varint,21,opt,name=bid_count,json=bidCount,proto3" json:"bid_count,omitempty"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_34eef7f9fdca6f38, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Task.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return m.Size()
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetRequesterId() string {
	if m != nil {
		return m.RequesterId
	}
	return ""
}

func (m *Task) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

func (m *Task) GetTaskType() TaskType {
	if m != nil {
		return m.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (m *Task) GetCategory() TaskCategory {
	if m != nil {
		return m.Category
	}
	return TaskCategory_TASK_CATEGORY_UNSPECIFIED
}

func (m *Task) GetStatus() TaskStatus {
	if m != nil {
		return m.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (m *Task) GetBudget() uint64 {
	if m != nil {
		return m.Budget
	}
	return 0
}

func (m *Task) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Task) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *Task) GetSkills() []string {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *Task) GetSubtasks() []Subtask {
	if m != nil {
		return m.Subtasks
	}
	return nil
}

func (m *Task) GetMilestones() []Milestone {
	if m != nil {
		return m.Milestones
	}
	return nil
}

func (m *Task) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Task) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Task) GetAssignedAt() int64 {
	if m != nil {
		return m.AssignedAt
	}
	return 0
}

func (m *Task) GetCompletedAt() int64 {
	if m != nil {
		return m.CompletedAt
	}
	return 0
}

func (m *Task) GetViewCount() int32 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

func (m *Task) GetApplicationCount() int32 {
	if m != nil {
		return m.ApplicationCount
	}
	return 0
}

func (m *Task) GetBidCount() int32 {
	if m != nil {
		return m.BidCount
	}
	return 0
}

// Subtask represents a decomposed subtask
type Subtask struct {
	// id is the unique subtask identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// task_id is the parent task ID
	TaskId string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// title is the subtask title
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// description is the subtask description
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// order is the display order
	Order int32 `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	// budget is the subtask budget
	Budget uint64 `protobuf:"varint,6,opt,name=budget,proto3" json:"budget,omitempty"`
	// completed indicates if the subtask is completed
	Completed bool `protobuf:"varint,7,opt,name=completed,proto3" json:"completed,omitempty"`
}

func (m *Subtask) Reset()         { *m = Subtask{} }
func (m *Subtask) String() string { return proto.CompactTextString(m) }
func (*Subtask) ProtoMessage()    {}
func (*Subtask) Descriptor() ([]byte, []int) {
	return fileDescriptor_34eef7f9fdca6f38, []int{1}
}
func (m *Subtask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Subtask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Subtask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Subtask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subtask.Merge(m, src)
}
func (m *Subtask) XXX_Size() int {
	return m.Size()
}
func (m *Subtask) XXX_DiscardUnknown() {
	xxx_messageInfo_Subtask.DiscardUnknown(m)
}

var xxx_messageInfo_Subtask proto.InternalMessageInfo

func (m *Subtask) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subtask) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *Subtask) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Subtask) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Subtask) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *Subtask) GetBudget() uint64 {
	if m != nil {
		return m.Budget
	}
	return 0
}

func (m *Subtask) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

// Milestone represents a task milestone
type Milestone struct {
	// id is the unique milestone identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// task_id is the parent task ID
	TaskId string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// title is the milestone title
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// description is the milestone description
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// amount is the milestone payment amount
	Amount uint64 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// order is the display order
	Order int32 `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	// status is the milestone status
	Status MilestoneStatus `protobuf:"varint,7,opt,name=status,proto3,enum=sharetoken.taskmarket.MilestoneStatus" json:"status,omitempty"`
	// deliverables is the submitted deliverables
	Deliverables string `protobuf:"bytes,8,opt,name=deliverables,proto3" json:"deliverables,omitempty"`
	// created_at is the Unix timestamp of creation
	CreatedAt int64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// completed_at is the Unix timestamp of completion
	CompletedAt int64 `protobuf:"varint,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
}

func (m *Milestone) Reset()         { *m = Milestone{} }
func (m *Milestone) String() string { return proto.CompactTextString(m) }
func (*Milestone) ProtoMessage()    {}
func (*Milestone) Descriptor() ([]byte, []int) {
	return fileDescriptor_34eef7f9fdca6f38, []int{2}
}
func (m *Milestone) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Milestone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Milestone.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Milestone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Milestone.Merge(m, src)
}
func (m *Milestone) XXX_Size() int {
	return m.Size()
}
func (m *Milestone) XXX_DiscardUnknown() {
	xxx_messageInfo_Milestone.DiscardUnknown(m)
}

var xxx_messageInfo_Milestone proto.InternalMessageInfo

func (m *Milestone) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Milestone) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *Milestone) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Milestone) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Milestone) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Milestone) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *Milestone) GetStatus() MilestoneStatus {
	if m != nil {
		return m.Status
	}
	return MilestoneStatus_MILESTONE_STATUS_UNSPECIFIED
}

func (m *Milestone) GetDeliverables() string {
	if m != nil {
		return m.Deliverables
	}
	return ""
}

func (m *Milestone) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Milestone) GetCompletedAt() int64 {
	if m != nil {
		return m.CompletedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("sharetoken.taskmarket.TaskType", TaskType_name, TaskType_value)
	proto.RegisterEnum("sharetoken.taskmarket.TaskStatus", TaskStatus_name, TaskStatus_value)
	proto.RegisterEnum("sharetoken.taskmarket.TaskCategory", TaskCategory_name, TaskCategory_value)
	proto.RegisterEnum("sharetoken.taskmarket.MilestoneStatus", MilestoneStatus_name, MilestoneStatus_value)
	proto.RegisterType((*Task)(nil), "sharetoken.taskmarket.Task")
	proto.RegisterType((*Subtask)(nil), "sharetoken.taskmarket.Subtask")
	proto.RegisterType((*Milestone)(nil), "sharetoken.taskmarket.Milestone")
}

func init() { proto.RegisterFile("sharetoken/taskmarket/task.proto", fileDescriptor_34eef7f9fdca6f38) }

var fileDescriptor_34eef7f9fdca6f38 = []byte{
	// 1023 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x35, 0xf5, 0x41, 0x8b, 0x63, 0xd7, 0xa1, 0x37, 0xb2, 0x4d, 0x7f, 0xc9, 0x8c, 0x0b, 0x14,
	0x82, 0x0b, 0xd8, 0x40, 0x7a, 0x28, 0x0a, 0x14, 0x6d, 0x69, 0x6a, 0xed, 0xb0, 0x91, 0x28, 0x62,
	0x49, 0x39, 0x48, 0x2f, 0x02, 0x25, 0x2e, 0x5c, 0x42, 0xb2, 0xa8, 0x92, 0xab, 0xa4, 0xfe, 0x17,
	0xfd, 0x13, 0xfd, 0x0b, 0x3d, 0xf7, 0x98, 0x63, 0x8e, 0x3d, 0x15, 0x85, 0x7d, 0xe8, 0xb9, 0x87,
	0xde, 0x0b, 0x2e, 0x29, 0x8a, 0x92, 0x1c, 0xf7, 0x94, 0x8b, 0xc0, 0x79, 0xef, 0xcd, 0xec, 0xcc,
	0xea, 0x0d, 0x41, 0x50, 0xa3, 0x1f, 0xdd, 0x90, 0xb2, 0x60, 0x40, 0x47, 0x67, 0xcc, 0x8d, 0x06,
	0x37, 0x6e, 0x38, 0xa0, 0x8c, 0x3f, 0x9e, 0x8e, 0xc3, 0x80, 0x05, 0x68, 0x6b, 0xa6, 0x38, 0x9d,
	0x29, 0xf6, 0x36, 0xdd, 0x1b, 0x7f, 0x14, 0x9c, 0xf1, 0xdf, 0x44, 0xb9, 0x57, 0xbd, 0x0e, 0xae,
	0x03, 0xfe, 0x78, 0x16, 0x3f, 0x25, 0xe8, 0xf1, 0xaf, 0x22, 0x94, 0x1c, 0x37, 0x1a, 0xa0, 0x0d,
	0x28, 0xf8, 0x9e, 0x22, 0xa8, 0x42, 0x5d, 0x22, 0x05, 0xdf, 0x43, 0x55, 0x28, 0x33, 0x9f, 0x0d,
	0xa9, 0x52, 0xe0, 0x50, 0x12, 0x20, 0x15, 0xd6, 0x3c, 0x1a, 0xf5, 0x43, 0x7f, 0xcc, 0xfc, 0x60,
	0xa4, 0x14, 0x39, 0x97, 0x87, 0xd0, 0x33, 0x58, 0x0f, 0xe9, 0x4f, 0x13, 0x1a, 0x31, 0x1a, 0x76,
	0x7d, 0x4f, 0x29, 0x25, 0x92, 0x0c, 0x33, 0x3c, 0xb4, 0x0f, 0xd2, 0xdb, 0x20, 0x1c, 0x24, 0x7c,
	0x99, 0xf3, 0x95, 0x04, 0x30, 0x3c, 0xf4, 0x35, 0x48, 0xf1, 0x1c, 0x5d, 0x76, 0x3b, 0xa6, 0x8a,
	0xa8, 0x0a, 0xf5, 0x8d, 0xe7, 0x47, 0xa7, 0x0f, 0x0e, 0x79, 0x1a, 0xf7, 0xed, 0xdc, 0x8e, 0x29,
	0xa9, 0xb0, 0xf4, 0x09, 0x7d, 0x0b, 0x95, 0xbe, 0xcb, 0xe8, 0x75, 0x10, 0xde, 0x2a, 0xab, 0x3c,
	0xf9, 0xd3, 0x47, 0x92, 0xf5, 0x54, 0x4a, 0xb2, 0x24, 0xf4, 0x15, 0x88, 0x11, 0x73, 0xd9, 0x24,
	0x52, 0x2a, 0x3c, 0xfd, 0xd9, 0x23, 0xe9, 0x36, 0x17, 0x92, 0x34, 0x01, 0x6d, 0x83, 0xd8, 0x9b,
	0x78, 0xd7, 0x94, 0x29, 0x92, 0x2a, 0xd4, 0x4b, 0x24, 0x8d, 0xd0, 0x1e, 0x54, 0xfa, 0x93, 0x30,
	0xa4, 0xa3, 0xfe, 0xad, 0x02, 0xc9, 0xb4, 0xd3, 0x38, 0xe6, 0x3c, 0xea, 0x7a, 0x43, 0x7f, 0x44,
	0x95, 0x35, 0x55, 0xa8, 0x17, 0x49, 0x16, 0xc7, 0xf5, 0xa2, 0x81, 0x3f, 0x1c, 0x46, 0xca, 0xba,
	0x5a, 0xac, 0x4b, 0x24, 0x8d, 0xd0, 0x77, 0x50, 0x89, 0x26, 0xbd, 0xb8, 0x97, 0x48, 0xf9, 0x44,
	0x2d, 0xd6, 0xd7, 0x9e, 0xd7, 0x3e, 0xd0, 0xa4, 0x9d, 0xc8, 0xce, 0x4b, 0xef, 0xfe, 0x3c, 0x5a,
	0x21, 0x59, 0x16, 0xba, 0x00, 0xb8, 0xf1, 0x87, 0x34, 0x62, 0xc1, 0x88, 0x46, 0xca, 0x06, 0xaf,
	0xa1, 0x7e, 0xa0, 0x46, 0x6b, 0x2a, 0x4c, 0xab, 0xe4, 0x32, 0xd1, 0x21, 0x40, 0x3f, 0xa4, 0x2e,
	0xa3, 0x5e, 0xd7, 0x65, 0xca, 0x13, 0xde, 0xbf, 0x94, 0x22, 0x1a, 0x8b, 0xe9, 0xc9, 0xd8, 0x9b,
	0xd2, 0x72, 0x42, 0xa7, 0x88, 0xc6, 0xd0, 0x11, 0xac, 0xb9, 0x51, 0xe4, 0x5f, 0x8f, 0x12, 0x7e,
	0x93, 0xf3, 0x30, 0x85, 0x34, 0x16, 0x5b, 0xa9, 0x1f, 0xdc, 0x8c, 0x87, 0x34, 0xad, 0x80, 0xb8,
	0x62, 0x2d, 0xc3, 0x92, 0x23, 0xde, 0xf8, 0xf4, 0x6d, 0xb7, 0x1f, 0x4c, 0x46, 0x4c, 0x79, 0xaa,
	0x0a, 0xf5, 0x32, 0x91, 0x62, 0x44, 0x8f, 0x01, 0xf4, 0x39, 0x6c, 0xba, 0xe3, 0xf1, 0xd0, 0xef,
	0xbb, 0xb1, 0x37, 0x53, 0x55, 0x95, 0xab, 0xe4, 0x1c, 0x91, 0x88, 0xf7, 0x41, 0xea, 0xf9, 0x5e,
	0x2a, 0xda, 0xe2, 0xa2, 0x4a, 0xcf, 0xf7, 0x38, 0x79, 0xfc, 0x9b, 0x00, 0xab, 0xe9, 0x75, 0x2e,
	0xad, 0xca, 0x0e, 0xac, 0x72, 0xcb, 0xfa, 0x5e, 0xba, 0x2c, 0x62, 0x1c, 0x1a, 0xb9, 0x1d, 0x2a,
	0x3e, 0xb2, 0x43, 0xa5, 0xe5, 0x1d, 0xaa, 0x42, 0x39, 0x08, 0x3d, 0x1a, 0xf2, 0xe5, 0x28, 0x93,
	0x24, 0xc8, 0xf9, 0x4b, 0x9c, 0xf3, 0xd7, 0x01, 0x48, 0xd9, 0x95, 0x70, 0xd3, 0x57, 0xc8, 0x0c,
	0x38, 0xfe, 0xbd, 0x00, 0x52, 0xf6, 0x1f, 0x7e, 0xfc, 0xd6, 0xb7, 0x41, 0x74, 0x6f, 0xf8, 0x0d,
	0x96, 0x93, 0x26, 0x93, 0x68, 0x36, 0x92, 0x98, 0x1f, 0xe9, 0x9b, 0x6c, 0xdb, 0x92, 0x65, 0xfd,
	0xec, 0xff, 0x4c, 0xb8, 0xb0, 0x72, 0xc7, 0xb0, 0xee, 0xd1, 0xa1, 0xff, 0x86, 0x86, 0x6e, 0x6f,
	0x48, 0x93, 0x9d, 0x95, 0xc8, 0x1c, 0xb6, 0x60, 0x52, 0x69, 0xd1, 0xa4, 0x8b, 0x26, 0x83, 0x25,
	0x93, 0x9d, 0x58, 0x50, 0x99, 0xbe, 0x6a, 0xd0, 0x2e, 0x6c, 0x39, 0x9a, 0xfd, 0xb2, 0xeb, 0xbc,
	0xb6, 0x70, 0xb7, 0x63, 0xda, 0x16, 0xd6, 0x8d, 0x0b, 0x03, 0x37, 0xe4, 0x15, 0x84, 0x60, 0x63,
	0x46, 0xb5, 0x2d, 0x6c, 0xca, 0x02, 0xda, 0x82, 0xcd, 0x19, 0xa6, 0x75, 0x74, 0xc7, 0x68, 0x9b,
	0x72, 0xe1, 0xe4, 0x5f, 0x01, 0x60, 0xf6, 0x06, 0x41, 0xfb, 0xb0, 0xc3, 0x55, 0xb6, 0xa3, 0x39,
	0x1d, 0x7b, 0xa1, 0xec, 0xb4, 0x44, 0x4a, 0x36, 0x88, 0x76, 0xe1, 0xc8, 0x02, 0xaa, 0x82, 0x9c,
	0x87, 0xf9, 0x79, 0x05, 0xa4, 0x40, 0x35, 0x8f, 0x6a, 0xb6, 0x6d, 0x5c, 0x9a, 0xb8, 0x21, 0x17,
	0x17, 0xcf, 0x30, 0xcc, 0xae, 0x45, 0xda, 0x97, 0x04, 0xdb, 0xb6, 0x5c, 0x42, 0xdb, 0x80, 0xf2,
	0x24, 0xc1, 0x57, 0x06, 0x7e, 0x25, 0x97, 0xb3, 0x69, 0x53, 0x5c, 0x6f, 0xb7, 0xac, 0x26, 0x76,
	0x70, 0x43, 0x16, 0x97, 0x28, 0xcd, 0xd4, 0x71, 0xb3, 0x89, 0x1b, 0xf2, 0xea, 0x62, 0x13, 0x0d,
	0xc3, 0xb6, 0x3a, 0x71, 0x52, 0xe5, 0xe4, 0x1f, 0x01, 0xd6, 0xf3, 0x2f, 0x5e, 0x74, 0x08, 0xbb,
	0x5c, 0xaa, 0x6b, 0x0e, 0xbe, 0x6c, 0x93, 0xd7, 0x0b, 0xb3, 0x2f, 0xd1, 0x0d, 0x7c, 0x85, 0x9b,
	0x6d, 0xab, 0x85, 0xcd, 0xf8, 0x0e, 0xa6, 0x07, 0xe5, 0xe8, 0x78, 0x5e, 0xb9, 0x90, 0x75, 0x97,
	0x31, 0xaf, 0x88, 0xe1, 0x18, 0xe6, 0xa5, 0x5c, 0x44, 0x7b, 0xb0, 0x3d, 0x4f, 0x11, 0x6c, 0x63,
	0x8d, 0xe8, 0x2f, 0xe4, 0x52, 0x76, 0x49, 0x19, 0xd7, 0xd2, 0xc8, 0x4b, 0xcc, 0x13, 0xcb, 0xe8,
	0x00, 0x94, 0x79, 0x52, 0x6f, 0x9b, 0x76, 0xa7, 0xc9, 0x59, 0x11, 0xed, 0xc0, 0xd3, 0x79, 0xb6,
	0xed, 0xbc, 0xc0, 0x44, 0x5e, 0x3d, 0xf9, 0x5b, 0x80, 0x27, 0x0b, 0xfe, 0x45, 0x2a, 0x1c, 0xb4,
	0x8c, 0x26, 0xb6, 0x9d, 0xb6, 0x89, 0x1f, 0xfe, 0xd7, 0x0f, 0x40, 0x59, 0x52, 0x58, 0xd8, 0x6c,
	0xc4, 0x87, 0x09, 0x71, 0x9f, 0x4b, 0xac, 0xa6, 0x3b, 0xc6, 0x15, 0x96, 0x0b, 0xa8, 0x06, 0x7b,
	0x4b, 0xa4, 0xdd, 0x39, 0x6f, 0x19, 0x8e, 0xc3, 0x9d, 0x70, 0x08, 0xbb, 0xcb, 0xc9, 0x96, 0x45,
	0xda, 0x57, 0xb8, 0x21, 0x97, 0x1e, 0xa4, 0x09, 0xfe, 0x1e, 0xeb, 0x71, 0x36, 0xb7, 0xc4, 0x72,
	0x63, 0x9a, 0xd1, 0x90, 0xc5, 0xf3, 0x2f, 0xdf, 0xdd, 0xd5, 0x84, 0xf7, 0x77, 0x35, 0xe1, 0xaf,
	0xbb, 0x9a, 0xf0, 0xcb, 0x7d, 0x6d, 0xe5, 0xfd, 0x7d, 0x6d, 0xe5, 0x8f, 0xfb, 0xda, 0xca, 0x0f,
	0x87, 0xb9, 0xef, 0x98, 0x9f, 0xe7, 0xbe, 0x64, 0x6e, 0xc7, 0x34, 0xea, 0x89, 0xfc, 0x5b, 0xe4,
	0x8b, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x44, 0xfb, 0xae, 0xef, 0x08, 0x00, 0x00,
}

func (m *Task) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Task) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BidCount != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.BidCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.ApplicationCount != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.ApplicationCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.ViewCount != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.ViewCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.CompletedAt != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.CompletedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.AssignedAt != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.AssignedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.CreatedAt != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x78
	}
	if len(m.Milestones) > 0 {
		for iNdEx := len(m.Milestones) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Milestones[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTask(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.Subtasks) > 0 {
		for iNdEx := len(m.Subtasks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Subtasks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTask(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.Skills) > 0 {
		for iNdEx := len(m.Skills) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Skills[iNdEx])
			copy(dAtA[i:], m.Skills[iNdEx])
			i = encodeVarintTask(dAtA, i, uint64(len(m.Skills[iNdEx])))
			i--
			dAtA[i] = 0x62
		}
	}
	if m.Deadline != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Deadline))
		i--
		dAtA[i] = 0x58
	}
	if len(m.Currency) > 0 {
		i -= len(m.Currency)
		copy(dAtA[i:], m.Currency)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Currency)))
		i--
		dAtA[i] = 0x52
	}
	if m.Budget != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Budget))
		i--
		dAtA[i] = 0x48
	}
	if m.Status != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if m.Category != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Category))
		i--
		dAtA[i] = 0x38
	}
	if m.TaskType != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.TaskType))
		i--
		dAtA[i] = 0x30
	}
	if len(m.WorkerId) > 0 {
		i -= len(m.WorkerId)
		copy(dAtA[i:], m.WorkerId)
		i = encodeVarintTask(dAtA, i, uint64(len(m.WorkerId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RequesterId) > 0 {
		i -= len(m.RequesterId)
		copy(dAtA[i:], m.RequesterId)
		i = encodeVarintTask(dAtA, i, uint64(len(m.RequesterId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Subtask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Subtask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Subtask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Completed {
		i--
		if m.Completed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Budget != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Budget))
		i--
		dAtA[i] = 0x30
	}
	if m.Order != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Order))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTask(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Milestone) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Milestone) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Milestone) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompletedAt != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.CompletedAt))
		i--
		dAtA[i] = 0x50
	}
	if m.CreatedAt != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Deliverables) > 0 {
		i -= len(m.Deliverables)
		copy(dAtA[i:], m.Deliverables)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Deliverables)))
		i--
		dAtA[i] = 0x42
	}
	if m.Status != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.Order != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Order))
		i--
		dAtA[i] = 0x30
	}
	if m.Amount != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTask(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTask(dAtA []byte, offset int, v uint64) int {
	offset -= sovTask(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Task) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.RequesterId)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.WorkerId)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.TaskType != 0 {
		n += 1 + sovTask(uint64(m.TaskType))
	}
	if m.Category != 0 {
		n += 1 + sovTask(uint64(m.Category))
	}
	if m.Status != 0 {
		n += 1 + sovTask(uint64(m.Status))
	}
	if m.Budget != 0 {
		n += 1 + sovTask(uint64(m.Budget))
	}
	l = len(m.Currency)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.Deadline != 0 {
		n += 1 + sovTask(uint64(m.Deadline))
	}
	if len(m.Skills) > 0 {
		for _, s := range m.Skills {
			l = len(s)
			n += 1 + l + sovTask(uint64(l))
		}
	}
	if len(m.Subtasks) > 0 {
		for _, e := range m.Subtasks {
			l = e.Size()
			n += 1 + l + sovTask(uint64(l))
		}
	}
	if len(m.Milestones) > 0 {
		for _, e := range m.Milestones {
			l = e.Size()
			n += 1 + l + sovTask(uint64(l))
		}
	}
	if m.CreatedAt != 0 {
		n += 1 + sovTask(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 2 + sovTask(uint64(m.UpdatedAt))
	}
	if m.AssignedAt != 0 {
		n += 2 + sovTask(uint64(m.AssignedAt))
	}
	if m.CompletedAt != 0 {
		n += 2 + sovTask(uint64(m.CompletedAt))
	}
	if m.ViewCount != 0 {
		n += 2 + sovTask(uint64(m.ViewCount))
	}
	if m.ApplicationCount != 0 {
		n += 2 + sovTask(uint64(m.ApplicationCount))
	}
	if m.BidCount != 0 {
		n += 2 + sovTask(uint64(m.BidCount))
	}
	return n
}

func (m *Subtask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.Order != 0 {
		n += 1 + sovTask(uint64(m.Order))
	}
	if m.Budget != 0 {
		n += 1 + sovTask(uint64(m.Budget))
	}
	if m.Completed {
		n += 2
	}
	return n
}

func (m *Milestone) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTask(uint64(m.Amount))
	}
	if m.Order != 0 {
		n += 1 + sovTask(uint64(m.Order))
	}
	if m.Status != 0 {
		n += 1 + sovTask(uint64(m.Status))
	}
	l = len(m.Deliverables)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovTask(uint64(m.CreatedAt))
	}
	if m.CompletedAt != 0 {
		n += 1 + sovTask(uint64(m.CompletedAt))
	}
	return n
}

func sovTask(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTask(x uint64) (n int) {
	return sovTask(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Task) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Task: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Task: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskType", wireType)
			}
			m.TaskType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskType |= TaskType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			m.Category = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Category |= TaskCategory(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= TaskStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Budget", wireType)
			}
			m.Budget = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Budget |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Currency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			m.Deadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skills", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skills = append(m.Skills, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subtasks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subtasks = append(m.Subtasks, Subtask{})
			if err := m.Subtasks[len(m.Subtasks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Milestones", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Milestones = append(m.Milestones, Milestone{})
			if err := m.Milestones[len(m.Milestones)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssignedAt", wireType)
			}
			m.AssignedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssignedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAt", wireType)
			}
			m.CompletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ViewCount", wireType)
			}
			m.ViewCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ViewCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationCount", wireType)
			}
			m.ApplicationCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidCount", wireType)
			}
			m.BidCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BidCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Subtask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Subtask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Subtask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			m.Order = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Order |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Budget", wireType)
			}
			m.Budget = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Budget |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Completed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Completed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Milestone) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Milestone: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Milestone: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			m.Order = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Order |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= MilestoneStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deliverables", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deliverables = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAt", wireType)
			}
			m.CompletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTask(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTask
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTask
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTask
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTask
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTask        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTask          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTask = fmt.Errorf("proto: unexpected end of group")
)
