// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sharetoken/crowdfunding/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the crowdfunding module's genesis state.
type GenesisState struct {
	// ideas is the list of ideas
	Ideas []Idea `protobuf:"bytes,1,rep,name=ideas,proto3" json:"ideas"`
	// campaigns is the list of campaigns
	Campaigns []Campaign `protobuf:"bytes,2,rep,name=campaigns,proto3" json:"campaigns"`
	// backers is the list of backers
	Backers []Backer `protobuf:"bytes,3,rep,name=backers,proto3" json:"backers"`
	// contributions is the list of contributions
	Contributions []Contribution `protobuf:"bytes,4,rep,name=contributions,proto3" json:"contributions"`
	// updates is the list of campaign updates
	Updates []CampaignUpdate `protobuf:"bytes,5,rep,name=updates,proto3" json:"updates"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_101b49140dfeda7e, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetIdeas() []Idea {
	if m != nil {
		return m.Ideas
	}
	return nil
}

func (m *GenesisState) GetCampaigns() []Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *GenesisState) GetBackers() []Backer {
	if m != nil {
		return m.Backers
	}
	return nil
}

func (m *GenesisState) GetContributions() []Contribution {
	if m != nil {
		return m.Contributions
	}
	return nil
}

func (m *GenesisState) GetUpdates() []CampaignUpdate {
	if m != nil {
		return m.Updates
	}
	return nil
}

// Params defines the parameters for the crowdfunding module.
type Params struct {
	// min_campaign_duration is the minimum campaign duration in seconds
	MinCampaignDuration int64 `protobuf:"varint,1,opt,name=min_campaign_duration,json=minCampaignDuration,proto3" json:"min_campaign_duration,omitempty"`
	// max_campaign_duration is the maximum campaign duration in seconds
	MaxCampaignDuration int64 `protobuf:"varint,2,opt,name=max_campaign_duration,json=maxCampaignDuration,proto3" json:"max_campaign_duration,omitempty"`
	// min_goal_amount is the minimum goal amount
	MinGoalAmount uint64 `protobuf:"varint,3,opt,name=min_goal_amount,json=minGoalAmount,proto3" json:"min_goal_amount,omitempty"`
	// max_goal_amount is the maximum goal amount
	MaxGoalAmount uint64 `protobuf:"varint,4,opt,name=max_goal_amount,json=maxGoalAmount,proto3" json:"max_goal_amount,omitempty"`
	// platform_fee_rate is the platform fee rate (basis points)
	PlatformFeeRate uint32 `protobuf:"varint,5,opt,name=platform_fee_rate,json=platformFeeRate,proto3" json:"platform_fee_rate,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_101b49140dfeda7e, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinCampaignDuration() int64 {
	if m != nil {
		return m.MinCampaignDuration
	}
	return 0
}

func (m *Params) GetMaxCampaignDuration() int64 {
	if m != nil {
		return m.MaxCampaignDuration
	}
	return 0
}

func (m *Params) GetMinGoalAmount() uint64 {
	if m != nil {
		return m.MinGoalAmount
	}
	return 0
}

func (m *Params) GetMaxGoalAmount() uint64 {
	if m != nil {
		return m.MaxGoalAmount
	}
	return 0
}

func (m *Params) GetPlatformFeeRate() uint32 {
	if m != nil {
		return m.PlatformFeeRate
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "sharetoken.crowdfunding.GenesisState")
	proto.RegisterType((*Params)(nil), "sharetoken.crowdfunding.Params")
}

func init() {
	proto.RegisterFile("sharetoken/crowdfunding/genesis.proto", fileDescriptor_101b49140dfeda7e)
}

var fileDescriptor_101b49140dfeda7e = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbd, 0x8e, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0xf9, 0xb8, 0x13, 0x0b, 0xd1, 0xe9, 0x0c, 0x08, 0xeb, 0x24, 0x1c, 0x13, 0xe9,
	0x8e, 0x70, 0x45, 0x22, 0x1d, 0xd5, 0xd1, 0x20, 0xc2, 0x47, 0x44, 0x07, 0x46, 0x34, 0x34, 0xd6,
	0x24, 0x9e, 0x98, 0xd5, 0x65, 0x77, 0xad, 0xdd, 0xb5, 0x30, 0xaf, 0x40, 0x45, 0x47, 0xcb, 0x23,
	0xf0, 0x18, 0x57, 0x5e, 0x49, 0x85, 0x50, 0x52, 0x40, 0xc3, 0x3b, 0xa0, 0xac, 0xd7, 0xba, 0x44,
	0x60, 0x5d, 0x63, 0xad, 0x76, 0x7f, 0xff, 0xdf, 0xcc, 0x58, 0x43, 0x0f, 0xf5, 0x7b, 0x50, 0x68,
	0xe4, 0x19, 0x8a, 0xd1, 0x4c, 0xc9, 0x0f, 0xc9, 0x3c, 0x17, 0x09, 0x13, 0xe9, 0x28, 0x45, 0x81,
	0x9a, 0xe9, 0x61, 0xa6, 0xa4, 0x91, 0xde, 0x9d, 0x4b, 0x6c, 0xb8, 0x89, 0x1d, 0xec, 0x03, 0x67,
	0x42, 0x8e, 0xec, 0xb7, 0x64, 0x0f, 0x6e, 0xa5, 0x32, 0x95, 0xf6, 0x38, 0x5a, 0x9f, 0xdc, 0x6d,
	0xbf, 0xae, 0x10, 0x4b, 0x10, 0x1c, 0x73, 0x54, 0xc7, 0xcc, 0x80, 0x67, 0xc0, 0x52, 0x51, 0x72,
	0xfd, 0x3f, 0x4d, 0x7a, 0x63, 0x52, 0xf6, 0xf7, 0xc6, 0x80, 0x41, 0xef, 0x94, 0x76, 0xd6, 0x1a,
	0xed, 0x93, 0xb0, 0x35, 0xb8, 0x7e, 0x72, 0x77, 0x58, 0xd3, 0xee, 0xf0, 0x65, 0x82, 0x30, 0x6e,
	0x9f, 0xff, 0xe8, 0x35, 0xa2, 0x32, 0xe1, 0x3d, 0xa7, 0xd7, 0x2a, 0xbb, 0xf6, 0x9b, 0x36, 0x7e,
	0xaf, 0x36, 0xfe, 0xd4, 0x91, 0x4e, 0x71, 0x99, 0xf4, 0x1e, 0xd3, 0xdd, 0x29, 0xcc, 0xce, 0x50,
	0x69, 0xbf, 0x65, 0x25, 0xbd, 0x5a, 0xc9, 0xd8, 0x72, 0x4e, 0x51, 0xa5, 0xbc, 0xd7, 0xb4, 0x3b,
	0x93, 0xc2, 0x28, 0x36, 0xcd, 0x0d, 0x93, 0x42, 0xfb, 0x6d, 0xab, 0x39, 0xac, 0xef, 0x65, 0x83,
	0x76, 0xb2, 0x6d, 0x83, 0x37, 0xa1, 0xbb, 0x79, 0x96, 0x80, 0x41, 0xed, 0x77, 0xac, 0xec, 0xfe,
	0x95, 0x83, 0xbd, 0xb5, 0x7c, 0xd5, 0x9b, 0x4b, 0xf7, 0xbf, 0x34, 0xe9, 0xce, 0x2b, 0x50, 0xc0,
	0xb5, 0x77, 0x42, 0x6f, 0x73, 0x26, 0xe2, 0x6a, 0xf0, 0x38, 0xc9, 0x15, 0xac, 0xab, 0xf9, 0x24,
	0x24, 0x83, 0x56, 0x74, 0x93, 0x33, 0x51, 0xb9, 0x9e, 0xb9, 0x27, 0x9b, 0x81, 0xe2, 0x3f, 0x99,
	0xa6, 0xcb, 0x40, 0xf1, 0x4f, 0xe6, 0x88, 0xee, 0xad, 0xeb, 0xa4, 0x12, 0x16, 0x31, 0x70, 0x99,
	0x0b, 0xe3, 0xb7, 0x42, 0x32, 0x68, 0x47, 0x5d, 0xce, 0xc4, 0x44, 0xc2, 0xe2, 0x89, 0xbd, 0xb4,
	0x1c, 0x14, 0x5b, 0x5c, 0xdb, 0x71, 0x50, 0x6c, 0x70, 0xc7, 0x74, 0x3f, 0x5b, 0x80, 0x99, 0x4b,
	0xc5, 0xe3, 0x39, 0x62, 0xac, 0xc0, 0xa0, 0xdf, 0x09, 0xc9, 0xa0, 0x1b, 0xed, 0x55, 0x0f, 0x2f,
	0x10, 0x23, 0x30, 0xf8, 0xe8, 0xc1, 0xef, 0xaf, 0x3d, 0xf2, 0xe9, 0xd7, 0xb7, 0xe3, 0x70, 0x63,
	0x1f, 0x8b, 0xed, 0x8d, 0x2c, 0x7f, 0xc7, 0xf8, 0xf4, 0x7c, 0x19, 0x90, 0x8b, 0x65, 0x40, 0x7e,
	0x2e, 0x03, 0xf2, 0x79, 0x15, 0x34, 0x2e, 0x56, 0x41, 0xe3, 0xfb, 0x2a, 0x68, 0xbc, 0xeb, 0xd5,
	0x67, 0xcd, 0xc7, 0x0c, 0xf5, 0x74, 0xc7, 0xee, 0xf2, 0xc3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf3, 0x43, 0xfc, 0x8c, 0x82, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MinCampaignDuration != that1.MinCampaignDuration {
		return false
	}
	if this.MaxCampaignDuration != that1.MaxCampaignDuration {
		return false
	}
	if this.MinGoalAmount != that1.MinGoalAmount {
		return false
	}
	if this.MaxGoalAmount != that1.MaxGoalAmount {
		return false
	}
	if this.PlatformFeeRate != that1.PlatformFeeRate {
		return false
	}
	return true
}
func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Updates) > 0 {
		for iNdEx := len(m.Updates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Updates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Contributions) > 0 {
		for iNdEx := len(m.Contributions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Contributions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Backers) > 0 {
		for iNdEx := len(m.Backers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Backers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Campaigns) > 0 {
		for iNdEx := len(m.Campaigns) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Campaigns[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Ideas) > 0 {
		for iNdEx := len(m.Ideas) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ideas[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PlatformFeeRate != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PlatformFeeRate))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxGoalAmount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxGoalAmount))
		i--
		dAtA[i] = 0x20
	}
	if m.MinGoalAmount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MinGoalAmount))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxCampaignDuration != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxCampaignDuration))
		i--
		dAtA[i] = 0x10
	}
	if m.MinCampaignDuration != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MinCampaignDuration))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ideas) > 0 {
		for _, e := range m.Ideas {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Campaigns) > 0 {
		for _, e := range m.Campaigns {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Backers) > 0 {
		for _, e := range m.Backers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Contributions) > 0 {
		for _, e := range m.Contributions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Updates) > 0 {
		for _, e := range m.Updates {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinCampaignDuration != 0 {
		n += 1 + sovGenesis(uint64(m.MinCampaignDuration))
	}
	if m.MaxCampaignDuration != 0 {
		n += 1 + sovGenesis(uint64(m.MaxCampaignDuration))
	}
	if m.MinGoalAmount != 0 {
		n += 1 + sovGenesis(uint64(m.MinGoalAmount))
	}
	if m.MaxGoalAmount != 0 {
		n += 1 + sovGenesis(uint64(m.MaxGoalAmount))
	}
	if m.PlatformFeeRate != 0 {
		n += 1 + sovGenesis(uint64(m.PlatformFeeRate))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ideas", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ideas = append(m.Ideas, Idea{})
			if err := m.Ideas[len(m.Ideas)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Campaigns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Campaigns = append(m.Campaigns, Campaign{})
			if err := m.Campaigns[len(m.Campaigns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Backers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Backers = append(m.Backers, Backer{})
			if err := m.Backers[len(m.Backers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contributions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contributions = append(m.Contributions, Contribution{})
			if err := m.Contributions[len(m.Contributions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Updates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Updates = append(m.Updates, CampaignUpdate{})
			if err := m.Updates[len(m.Updates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCampaignDuration", wireType)
			}
			m.MinCampaignDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCampaignDuration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCampaignDuration", wireType)
			}
			m.MaxCampaignDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCampaignDuration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGoalAmount", wireType)
			}
			m.MinGoalAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinGoalAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGoalAmount", wireType)
			}
			m.MaxGoalAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGoalAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlatformFeeRate", wireType)
			}
			m.PlatformFeeRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlatformFeeRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
