// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sharetoken/trust/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MQScore represents a user's Moral Quotient score
type MQScore struct {
	// address is the user address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// score is the current MQ score (0-100)
	Score int32 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	// disputes is the number of disputes participated
	Disputes uint64 `protobuf:"varint,3,opt,name=disputes,proto3" json:"disputes,omitempty"`
	// consensus is the number of times voted with consensus
	Consensus uint64 `protobuf:"varint,4,opt,name=consensus,proto3" json:"consensus,omitempty"`
	// updated_at is the Unix timestamp of last update
	UpdatedAt int64 `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *MQScore) Reset()         { *m = MQScore{} }
func (m *MQScore) String() string { return proto.CompactTextString(m) }
func (*MQScore) ProtoMessage()    {}
func (*MQScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_07b2ada38d10b922, []int{0}
}
func (m *MQScore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MQScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MQScore.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MQScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MQScore.Merge(m, src)
}
func (m *MQScore) XXX_Size() int {
	return m.Size()
}
func (m *MQScore) XXX_DiscardUnknown() {
	xxx_messageInfo_MQScore.DiscardUnknown(m)
}

var xxx_messageInfo_MQScore proto.InternalMessageInfo

func (m *MQScore) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MQScore) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *MQScore) GetDisputes() uint64 {
	if m != nil {
		return m.Disputes
	}
	return 0
}

func (m *MQScore) GetConsensus() uint64 {
	if m != nil {
		return m.Consensus
	}
	return 0
}

func (m *MQScore) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// GenesisState defines the trust module's genesis state.
type GenesisState struct {
	// mq_scores is the list of MQ scores
	MqScores []MQScore `protobuf:"bytes,1,rep,name=mq_scores,json=mqScores,proto3" json:"mq_scores"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_07b2ada38d10b922, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetMqScores() []MQScore {
	if m != nil {
		return m.MqScores
	}
	return nil
}

// Params defines the parameters for the trust module.
type Params struct {
	// initial_mq is the starting MQ score for new users
	InitialMq int32 `protobuf:"varint,1,opt,name=initial_mq,json=initialMq,proto3" json:"initial_mq,omitempty"`
	// max_mq_loss_percent is the maximum percentage of MQ that can be lost in a single dispute
	MaxMqLossPercent int32 `protobuf:"varint,2,opt,name=max_mq_loss_percent,json=maxMqLossPercent,proto3" json:"max_mq_loss_percent,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_07b2ada38d10b922, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetInitialMq() int32 {
	if m != nil {
		return m.InitialMq
	}
	return 0
}

func (m *Params) GetMaxMqLossPercent() int32 {
	if m != nil {
		return m.MaxMqLossPercent
	}
	return 0
}

func init() {
	proto.RegisterType((*MQScore)(nil), "sharetoken.trust.MQScore")
	proto.RegisterType((*GenesisState)(nil), "sharetoken.trust.GenesisState")
	proto.RegisterType((*Params)(nil), "sharetoken.trust.Params")
}

func init() { proto.RegisterFile("sharetoken/trust/genesis.proto", fileDescriptor_07b2ada38d10b922) }

var fileDescriptor_07b2ada38d10b922 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xb1, 0x4e, 0xe3, 0x40,
	0x14, 0xf4, 0x5e, 0xe2, 0x24, 0xde, 0xbb, 0x22, 0xb7, 0x97, 0xc2, 0x89, 0xee, 0x1c, 0xcb, 0x95,
	0x75, 0xd2, 0xd9, 0x52, 0xae, 0x43, 0x34, 0xa4, 0xa1, 0x49, 0xa4, 0xe0, 0x74, 0x34, 0xd6, 0x12,
	0xaf, 0x82, 0x45, 0xd6, 0x6b, 0xfb, 0xad, 0xa5, 0xc0, 0x27, 0x50, 0x21, 0xbe, 0x80, 0x4f, 0xe0,
	0x33, 0x52, 0xa6, 0xa4, 0x42, 0x28, 0x29, 0xe0, 0x33, 0x50, 0xd6, 0x86, 0x20, 0x44, 0xb3, 0x7a,
	0x33, 0xf3, 0x56, 0xf3, 0x46, 0x83, 0x2d, 0x38, 0xa7, 0x39, 0x93, 0xe2, 0x82, 0x25, 0xbe, 0xcc,
	0x0b, 0x90, 0xfe, 0x9c, 0x25, 0x0c, 0x62, 0xf0, 0xd2, 0x5c, 0x48, 0x41, 0xda, 0x7b, 0xdd, 0x53,
	0x7a, 0xef, 0x27, 0xe5, 0x71, 0x22, 0x7c, 0xf5, 0x96, 0x4b, 0xbd, 0xce, 0x5c, 0xcc, 0x85, 0x1a,
	0xfd, 0xdd, 0x54, 0xb2, 0xce, 0x2d, 0xc2, 0xcd, 0xf1, 0xc9, 0x74, 0x26, 0x72, 0x46, 0x4c, 0xdc,
	0xa4, 0x51, 0x94, 0x33, 0x00, 0x13, 0xd9, 0xc8, 0x35, 0x82, 0x37, 0x48, 0x3a, 0x58, 0x87, 0xdd,
	0x8a, 0xf9, 0xcd, 0x46, 0xae, 0x1e, 0x94, 0x80, 0xf4, 0x70, 0x2b, 0x8a, 0x21, 0x2d, 0x24, 0x03,
	0xb3, 0x66, 0x23, 0xb7, 0x1e, 0xbc, 0x63, 0xf2, 0x1b, 0x1b, 0x33, 0x91, 0x00, 0x4b, 0xa0, 0x00,
	0xb3, 0xae, 0xc4, 0x3d, 0x41, 0xfe, 0x60, 0x5c, 0xa4, 0x11, 0x95, 0x2c, 0x0a, 0xa9, 0x34, 0x75,
	0x1b, 0xb9, 0xb5, 0xc0, 0xa8, 0x98, 0x23, 0xe9, 0x8c, 0xf0, 0x8f, 0xe3, 0x32, 0xe0, 0x54, 0x52,
	0xc9, 0xc8, 0x21, 0x36, 0x78, 0x16, 0x2a, 0xd3, 0xdd, 0x69, 0x35, 0xf7, 0xfb, 0xa0, 0xeb, 0x7d,
	0xce, 0xec, 0x55, 0x31, 0x86, 0xf5, 0xd5, 0x63, 0x5f, 0x0b, 0x5a, 0x3c, 0x53, 0x10, 0x9c, 0x2b,
	0xdc, 0x98, 0xd0, 0x9c, 0x72, 0x65, 0x1b, 0x27, 0xb1, 0x8c, 0xe9, 0x22, 0xe4, 0x99, 0xca, 0xa8,
	0x07, 0x46, 0xc5, 0x8c, 0x33, 0xf2, 0x0f, 0xff, 0xe2, 0x74, 0x19, 0xf2, 0x2c, 0x5c, 0x08, 0x80,
	0x30, 0x65, 0xf9, 0x8c, 0x25, 0xb2, 0xca, 0xdc, 0xe6, 0x74, 0x39, 0xce, 0x46, 0x02, 0x60, 0x52,
	0xf2, 0x07, 0xce, 0xcb, 0x5d, 0x1f, 0x5d, 0x3f, 0xdf, 0xff, 0xed, 0x7e, 0xa8, 0x67, 0x59, 0x15,
	0x54, 0x3a, 0x0e, 0x07, 0xab, 0x8d, 0x85, 0xd6, 0x1b, 0x0b, 0x3d, 0x6d, 0x2c, 0x74, 0xb3, 0xb5,
	0xb4, 0xf5, 0xd6, 0xd2, 0x1e, 0xb6, 0x96, 0x76, 0x6a, 0x7e, 0xf1, 0x49, 0x5e, 0xa6, 0x0c, 0xce,
	0x1a, 0xaa, 0x99, 0xff, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x17, 0xf6, 0x5d, 0xf6, 0x01,
	0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.InitialMq != that1.InitialMq {
		return false
	}
	if this.MaxMqLossPercent != that1.MaxMqLossPercent {
		return false
	}
	return true
}
func (m *MQScore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MQScore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MQScore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x28
	}
	if m.Consensus != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Consensus))
		i--
		dAtA[i] = 0x20
	}
	if m.Disputes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Disputes))
		i--
		dAtA[i] = 0x18
	}
	if m.Score != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Score))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MqScores) > 0 {
		for iNdEx := len(m.MqScores) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MqScores[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxMqLossPercent != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxMqLossPercent))
		i--
		dAtA[i] = 0x10
	}
	if m.InitialMq != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.InitialMq))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MQScore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Score != 0 {
		n += 1 + sovGenesis(uint64(m.Score))
	}
	if m.Disputes != 0 {
		n += 1 + sovGenesis(uint64(m.Disputes))
	}
	if m.Consensus != 0 {
		n += 1 + sovGenesis(uint64(m.Consensus))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovGenesis(uint64(m.UpdatedAt))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MqScores) > 0 {
		for _, e := range m.MqScores {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.InitialMq != 0 {
		n += 1 + sovGenesis(uint64(m.InitialMq))
	}
	if m.MaxMqLossPercent != 0 {
		n += 1 + sovGenesis(uint64(m.MaxMqLossPercent))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MQScore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MQScore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MQScore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disputes", wireType)
			}
			m.Disputes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Disputes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Consensus", wireType)
			}
			m.Consensus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Consensus |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MqScores", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MqScores = append(m.MqScores, MQScore{})
			if err := m.MqScores[len(m.MqScores)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialMq", wireType)
			}
			m.InitialMq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialMq |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMqLossPercent", wireType)
			}
			m.MaxMqLossPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMqLossPercent |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
