// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sharetoken/trust/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryMQScoreRequest is the request type for the Query/MQScore RPC method.
type QueryMQScoreRequest struct {
	// address is the user address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryMQScoreRequest) Reset()         { *m = QueryMQScoreRequest{} }
func (m *QueryMQScoreRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMQScoreRequest) ProtoMessage()    {}
func (*QueryMQScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa32625289d98575, []int{0}
}
func (m *QueryMQScoreRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMQScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMQScoreRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMQScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMQScoreRequest.Merge(m, src)
}
func (m *QueryMQScoreRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMQScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMQScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMQScoreRequest proto.InternalMessageInfo

func (m *QueryMQScoreRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryMQScoreResponse is the response type for the Query/MQScore RPC method.
type QueryMQScoreResponse struct {
	// mq_score is the user's MQ score
	MqScore MQScore `protobuf:"bytes,1,opt,name=mq_score,json=mqScore,proto3" json:"mq_score"`
}

func (m *QueryMQScoreResponse) Reset()         { *m = QueryMQScoreResponse{} }
func (m *QueryMQScoreResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMQScoreResponse) ProtoMessage()    {}
func (*QueryMQScoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa32625289d98575, []int{1}
}
func (m *QueryMQScoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMQScoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMQScoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMQScoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMQScoreResponse.Merge(m, src)
}
func (m *QueryMQScoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMQScoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMQScoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMQScoreResponse proto.InternalMessageInfo

func (m *QueryMQScoreResponse) GetMqScore() MQScore {
	if m != nil {
		return m.MqScore
	}
	return MQScore{}
}

// QueryMQScoresRequest is the request type for the Query/MQScores RPC method.
type QueryMQScoresRequest struct {
	// min_score filters by minimum score
	MinScore int32 `protobuf:"varint,1,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	// max_score filters by maximum score
	MaxScore int32 `protobuf:"varint,2,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	// pagination defines an optional pagination for the request
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMQScoresRequest) Reset()         { *m = QueryMQScoresRequest{} }
func (m *QueryMQScoresRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMQScoresRequest) ProtoMessage()    {}
func (*QueryMQScoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa32625289d98575, []int{2}
}
func (m *QueryMQScoresRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMQScoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMQScoresRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMQScoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMQScoresRequest.Merge(m, src)
}
func (m *QueryMQScoresRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMQScoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMQScoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMQScoresRequest proto.InternalMessageInfo

func (m *QueryMQScoresRequest) GetMinScore() int32 {
	if m != nil {
		return m.MinScore
	}
	return 0
}

func (m *QueryMQScoresRequest) GetMaxScore() int32 {
	if m != nil {
		return m.MaxScore
	}
	return 0
}

func (m *QueryMQScoresRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryMQScoresResponse is the response type for the Query/MQScores RPC method.
type QueryMQScoresResponse struct {
	// mq_scores is the list of MQ scores
	MqScores []MQScore `protobuf:"bytes,1,rep,name=mq_scores,json=mqScores,proto3" json:"mq_scores"`
	// pagination defines the pagination in the response
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMQScoresResponse) Reset()         { *m = QueryMQScoresResponse{} }
func (m *QueryMQScoresResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMQScoresResponse) ProtoMessage()    {}
func (*QueryMQScoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa32625289d98575, []int{3}
}
func (m *QueryMQScoresResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMQScoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMQScoresResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMQScoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMQScoresResponse.Merge(m, src)
}
func (m *QueryMQScoresResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMQScoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMQScoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMQScoresResponse proto.InternalMessageInfo

func (m *QueryMQScoresResponse) GetMqScores() []MQScore {
	if m != nil {
		return m.MqScores
	}
	return nil
}

func (m *QueryMQScoresResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryMQScoreRequest)(nil), "sharetoken.trust.QueryMQScoreRequest")
	proto.RegisterType((*QueryMQScoreResponse)(nil), "sharetoken.trust.QueryMQScoreResponse")
	proto.RegisterType((*QueryMQScoresRequest)(nil), "sharetoken.trust.QueryMQScoresRequest")
	proto.RegisterType((*QueryMQScoresResponse)(nil), "sharetoken.trust.QueryMQScoresResponse")
}

func init() { proto.RegisterFile("sharetoken/trust/query.proto", fileDescriptor_fa32625289d98575) }

var fileDescriptor_fa32625289d98575 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x77, 0x52, 0xeb, 0x66, 0xc7, 0x8b, 0x8c, 0xab, 0xc4, 0xb4, 0x8c, 0x35, 0x60, 0x2b,
	0x15, 0x66, 0xe8, 0x7a, 0x13, 0x4f, 0x3d, 0xe8, 0x49, 0xb0, 0xf1, 0xe6, 0x45, 0x66, 0xdb, 0x21,
	0x06, 0xcd, 0x4c, 0x92, 0x37, 0x2b, 0x5b, 0x44, 0x0f, 0x82, 0xe0, 0x4d, 0xc1, 0x8b, 0x27, 0x3f,
	0x83, 0x1f, 0xa3, 0xc7, 0x82, 0x17, 0x4f, 0x22, 0xbb, 0x82, 0x5f, 0x43, 0x32, 0x99, 0xb0, 0xd9,
	0x6e, 0x21, 0xbd, 0x65, 0xe6, 0xff, 0x7f, 0xef, 0xfd, 0xde, 0x7b, 0x13, 0xbc, 0x09, 0x2f, 0x45,
	0x29, 0x8d, 0x7e, 0x25, 0x15, 0x37, 0xe5, 0x04, 0x0c, 0x2f, 0x26, 0xb2, 0x3c, 0x66, 0x79, 0xa9,
	0x8d, 0x26, 0x57, 0x17, 0x2a, 0xb3, 0x6a, 0xb8, 0x7b, 0xa8, 0x21, 0xd3, 0xc0, 0xc7, 0x02, 0x64,
	0x6d, 0xe5, 0x6f, 0xf6, 0xc6, 0xd2, 0x88, 0x3d, 0x9e, 0x8b, 0x24, 0x55, 0xc2, 0xa4, 0x5a, 0xd5,
	0xd1, 0xe1, 0x86, 0xf3, 0x36, 0xb6, 0x76, 0xea, 0x70, 0x98, 0xe8, 0x44, 0xdb, 0x4f, 0x5e, 0x7d,
	0xb9, 0xdb, 0xcd, 0x44, 0xeb, 0xe4, 0xb5, 0xe4, 0x22, 0x4f, 0xb9, 0x50, 0x4a, 0x1b, 0x9b, 0x0f,
	0x9c, 0x4a, 0x57, 0x60, 0x13, 0xa9, 0x24, 0xa4, 0x4e, 0x8f, 0x38, 0xbe, 0x76, 0x50, 0x95, 0x78,
	0x72, 0xf0, 0xec, 0x50, 0x97, 0x32, 0x96, 0xc5, 0x44, 0x82, 0x21, 0x01, 0xee, 0x8b, 0xa3, 0xa3,
	0x52, 0x02, 0x04, 0x68, 0x0b, 0xdd, 0x1d, 0xc4, 0xcd, 0x31, 0x8a, 0xf1, 0x70, 0x39, 0x00, 0x72,
	0xad, 0x40, 0x92, 0x07, 0xd8, 0xcf, 0x8a, 0x17, 0x50, 0xdd, 0xd9, 0x90, 0x2b, 0xa3, 0x9b, 0xec,
	0xec, 0x28, 0x98, 0x0b, 0xda, 0xbf, 0x74, 0xf2, 0xfb, 0x56, 0x2f, 0xee, 0x67, 0x85, 0x3d, 0x46,
	0xdf, 0xd0, 0x72, 0x52, 0x68, 0x30, 0x36, 0xf0, 0x20, 0x4b, 0x55, 0x2b, 0xeb, 0x7a, 0xec, 0x67,
	0xa9, 0xb2, 0x26, 0x2b, 0x8a, 0xa9, 0x13, 0x3d, 0x27, 0x8a, 0x69, 0x2d, 0x3e, 0xc2, 0x78, 0x31,
	0xdc, 0x60, 0xcd, 0x02, 0x6d, 0xb3, 0x7a, 0xba, 0xac, 0xda, 0x04, 0xab, 0x27, 0xeb, 0x36, 0xc1,
	0x9e, 0x8a, 0xa4, 0x69, 0x3e, 0x6e, 0x45, 0x46, 0xdf, 0x11, 0xbe, 0x7e, 0x06, 0xcd, 0x35, 0xfc,
	0x10, 0x0f, 0x9a, 0x86, 0xab, 0x21, 0xad, 0x5d, 0xa4, 0x63, 0xdf, 0x75, 0x0c, 0xe4, 0xf1, 0x12,
	0x9f, 0x67, 0xf9, 0x76, 0x3a, 0xf9, 0xea, 0xd2, 0x6d, 0xc0, 0xd1, 0x67, 0x0f, 0xaf, 0x5b, 0x40,
	0xf2, 0x11, 0xe1, 0xbe, 0x2b, 0x47, 0xee, 0xac, 0x92, 0x9c, 0xb3, 0xe6, 0x70, 0xbb, 0xcb, 0x56,
	0x17, 0x8c, 0xee, 0x7d, 0xfa, 0xf7, 0x63, 0x17, 0x7d, 0xf8, 0xf9, 0xf7, 0xab, 0xb7, 0x45, 0x28,
	0x5f, 0x79, 0x53, 0x59, 0xc1, 0xdf, 0xba, 0x07, 0xf2, 0x8e, 0xbc, 0xc7, 0x7e, 0x33, 0x2c, 0xd2,
	0x51, 0xa0, 0x59, 0x74, 0xb8, 0xd3, 0xe9, 0x73, 0x24, 0xb7, 0x17, 0x24, 0x37, 0xc8, 0xf0, 0x3c,
	0x92, 0xfd, 0xd1, 0xc9, 0x8c, 0xa2, 0xd3, 0x19, 0x45, 0x7f, 0x66, 0x14, 0x7d, 0x99, 0xd3, 0xde,
	0xe9, 0x9c, 0xf6, 0x7e, 0xcd, 0x69, 0xef, 0x79, 0xd0, 0xb2, 0x4f, 0x5d, 0x80, 0x39, 0xce, 0x25,
	0x8c, 0x2f, 0xdb, 0xbf, 0xe1, 0xfe, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0xfc, 0xad, 0xb6,
	0xdc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// MQScore queries a user's MQ score
	MQScore(ctx context.Context, in *QueryMQScoreRequest, opts ...grpc.CallOption) (*QueryMQScoreResponse, error)
	// MQScores queries all MQ scores
	MQScores(ctx context.Context, in *QueryMQScoresRequest, opts ...grpc.CallOption) (*QueryMQScoresResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) MQScore(ctx context.Context, in *QueryMQScoreRequest, opts ...grpc.CallOption) (*QueryMQScoreResponse, error) {
	out := new(QueryMQScoreResponse)
	err := c.cc.Invoke(ctx, "/sharetoken.trust.Query/MQScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MQScores(ctx context.Context, in *QueryMQScoresRequest, opts ...grpc.CallOption) (*QueryMQScoresResponse, error) {
	out := new(QueryMQScoresResponse)
	err := c.cc.Invoke(ctx, "/sharetoken.trust.Query/MQScores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// MQScore queries a user's MQ score
	MQScore(context.Context, *QueryMQScoreRequest) (*QueryMQScoreResponse, error)
	// MQScores queries all MQ scores
	MQScores(context.Context, *QueryMQScoresRequest) (*QueryMQScoresResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) MQScore(ctx context.Context, req *QueryMQScoreRequest) (*QueryMQScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MQScore not implemented")
}
func (*UnimplementedQueryServer) MQScores(ctx context.Context, req *QueryMQScoresRequest) (*QueryMQScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MQScores not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_MQScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMQScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MQScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sharetoken.trust.Query/MQScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MQScore(ctx, req.(*QueryMQScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MQScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMQScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MQScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sharetoken.trust.Query/MQScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MQScores(ctx, req.(*QueryMQScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sharetoken.trust.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MQScore",
			Handler:    _Query_MQScore_Handler,
		},
		{
			MethodName: "MQScores",
			Handler:    _Query_MQScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sharetoken/trust/query.proto",
}

func (m *QueryMQScoreRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMQScoreRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMQScoreRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMQScoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMQScoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMQScoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MqScore.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMQScoresRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMQScoresRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMQScoresRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.MaxScore != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MaxScore))
		i--
		dAtA[i] = 0x10
	}
	if m.MinScore != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MinScore))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryMQScoresResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMQScoresResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMQScoresResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.MqScores) > 0 {
		for iNdEx := len(m.MqScores) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MqScores[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryMQScoreRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMQScoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MqScore.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMQScoresRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinScore != 0 {
		n += 1 + sovQuery(uint64(m.MinScore))
	}
	if m.MaxScore != 0 {
		n += 1 + sovQuery(uint64(m.MaxScore))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMQScoresResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MqScores) > 0 {
		for _, e := range m.MqScores {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryMQScoreRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMQScoreRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMQScoreRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMQScoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMQScoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMQScoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MqScore", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MqScore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMQScoresRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMQScoresRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMQScoresRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinScore", wireType)
			}
			m.MinScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinScore |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxScore", wireType)
			}
			m.MaxScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxScore |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMQScoresResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMQScoresResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMQScoresResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MqScores", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MqScores = append(m.MqScores, MQScore{})
			if err := m.MqScores[len(m.MqScores)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
