// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sharetoken/dispute/dispute.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DisputeStatus represents the status of a dispute
type DisputeStatus int32

const (
	DisputeStatus_DISPUTE_STATUS_UNSPECIFIED DisputeStatus = 0
	DisputeStatus_DISPUTE_STATUS_OPEN        DisputeStatus = 1
	DisputeStatus_DISPUTE_STATUS_MEDIATING   DisputeStatus = 2
	DisputeStatus_DISPUTE_STATUS_VOTING      DisputeStatus = 3
	DisputeStatus_DISPUTE_STATUS_RESOLVED    DisputeStatus = 4
	DisputeStatus_DISPUTE_STATUS_CANCELLED   DisputeStatus = 5
)

var DisputeStatus_name = map[int32]string{
	0: "DISPUTE_STATUS_UNSPECIFIED",
	1: "DISPUTE_STATUS_OPEN",
	2: "DISPUTE_STATUS_MEDIATING",
	3: "DISPUTE_STATUS_VOTING",
	4: "DISPUTE_STATUS_RESOLVED",
	5: "DISPUTE_STATUS_CANCELLED",
}

var DisputeStatus_value = map[string]int32{
	"DISPUTE_STATUS_UNSPECIFIED": 0,
	"DISPUTE_STATUS_OPEN":        1,
	"DISPUTE_STATUS_MEDIATING":   2,
	"DISPUTE_STATUS_VOTING":      3,
	"DISPUTE_STATUS_RESOLVED":    4,
	"DISPUTE_STATUS_CANCELLED":   5,
}

func (x DisputeStatus) String() string {
	return proto.EnumName(DisputeStatus_name, int32(x))
}

func (DisputeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b56a149ea2be05a, []int{0}
}

// Evidence represents evidence submitted in a dispute
type Evidence struct {
	// submitted_by is the address that submitted the evidence
	SubmittedBy string `protobuf:"bytes,1,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	// type is the evidence type
	EvidenceType string `protobuf:"bytes,2,opt,name=evidence_type,json=evidenceType,proto3" json:"evidence_type,omitempty"`
	// content is the evidence content
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// timestamp is the Unix timestamp of submission
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *Evidence) Reset()         { *m = Evidence{} }
func (m *Evidence) String() string { return proto.CompactTextString(m) }
func (*Evidence) ProtoMessage()    {}
func (*Evidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b56a149ea2be05a, []int{0}
}
func (m *Evidence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Evidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Evidence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Evidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Evidence.Merge(m, src)
}
func (m *Evidence) XXX_Size() int {
	return m.Size()
}
func (m *Evidence) XXX_DiscardUnknown() {
	xxx_messageInfo_Evidence.DiscardUnknown(m)
}

var xxx_messageInfo_Evidence proto.InternalMessageInfo

func (m *Evidence) GetSubmittedBy() string {
	if m != nil {
		return m.SubmittedBy
	}
	return ""
}

func (m *Evidence) GetEvidenceType() string {
	if m != nil {
		return m.EvidenceType
	}
	return ""
}

func (m *Evidence) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Evidence) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Vote represents a vote in a dispute
type Vote struct {
	// voter is the voter address
	Voter string `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	// weight is the voting weight
	Weight string `protobuf:"bytes,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// decision is the vote decision ("requester", "provider", or "split")
	Decision string `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	// timestamp is the Unix timestamp of voting
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b56a149ea2be05a, []int{1}
}
func (m *Vote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return m.Size()
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *Vote) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

func (m *Vote) GetDecision() string {
	if m != nil {
		return m.Decision
	}
	return ""
}

func (m *Vote) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// VoteResult represents the result of voting
type VoteResult struct {
	// decision is the final decision
	Decision string `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	// requester_votes is the total weight for requester
	RequesterVotes string `protobuf:"bytes,2,opt,name=requester_votes,json=requesterVotes,proto3" json:"requester_votes,omitempty"`
	// provider_votes is the total weight for provider
	ProviderVotes string `protobuf:"bytes,3,opt,name=provider_votes,json=providerVotes,proto3" json:"provider_votes,omitempty"`
	// split_votes is the total weight for split
	SplitVotes string `protobuf:"bytes,4,opt,name=split_votes,json=splitVotes,proto3" json:"split_votes,omitempty"`
	// total_weight is the total voting weight
	TotalWeight string `protobuf:"bytes,5,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
}

func (m *VoteResult) Reset()         { *m = VoteResult{} }
func (m *VoteResult) String() string { return proto.CompactTextString(m) }
func (*VoteResult) ProtoMessage()    {}
func (*VoteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b56a149ea2be05a, []int{2}
}
func (m *VoteResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VoteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VoteResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VoteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResult.Merge(m, src)
}
func (m *VoteResult) XXX_Size() int {
	return m.Size()
}
func (m *VoteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResult.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResult proto.InternalMessageInfo

func (m *VoteResult) GetDecision() string {
	if m != nil {
		return m.Decision
	}
	return ""
}

func (m *VoteResult) GetRequesterVotes() string {
	if m != nil {
		return m.RequesterVotes
	}
	return ""
}

func (m *VoteResult) GetProviderVotes() string {
	if m != nil {
		return m.ProviderVotes
	}
	return ""
}

func (m *VoteResult) GetSplitVotes() string {
	if m != nil {
		return m.SplitVotes
	}
	return ""
}

func (m *VoteResult) GetTotalWeight() string {
	if m != nil {
		return m.TotalWeight
	}
	return ""
}

// Dispute represents a dispute between parties
type Dispute struct {
	// id is the unique dispute identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// escrow_id is the associated escrow ID
	EscrowId string `protobuf:"bytes,2,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	// requester is the requester address
	Requester string `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	// provider is the provider address
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	// status is the dispute status
	Status DisputeStatus `protobuf:"varint,5,opt,name=status,proto3,enum=sharetoken.dispute.DisputeStatus" json:"status,omitempty"`
	// reason is the dispute reason
	Reason string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// evidence is the list of submitted evidence
	Evidence []Evidence `protobuf:"bytes,7,rep,name=evidence,proto3" json:"evidence"`
	// votes is the list of votes
	Votes []Vote `protobuf:"bytes,8,rep,name=votes,proto3" json:"votes"`
	// result is the voting result
	Result VoteResult `protobuf:"bytes,9,opt,name=result,proto3" json:"result"`
	// created_at is the Unix timestamp of creation
	CreatedAt int64 `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// completed_at is the Unix timestamp of completion
	CompletedAt int64 `protobuf:"varint,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
}

func (m *Dispute) Reset()         { *m = Dispute{} }
func (m *Dispute) String() string { return proto.CompactTextString(m) }
func (*Dispute) ProtoMessage()    {}
func (*Dispute) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b56a149ea2be05a, []int{3}
}
func (m *Dispute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Dispute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Dispute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Dispute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dispute.Merge(m, src)
}
func (m *Dispute) XXX_Size() int {
	return m.Size()
}
func (m *Dispute) XXX_DiscardUnknown() {
	xxx_messageInfo_Dispute.DiscardUnknown(m)
}

var xxx_messageInfo_Dispute proto.InternalMessageInfo

func (m *Dispute) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dispute) GetEscrowId() string {
	if m != nil {
		return m.EscrowId
	}
	return ""
}

func (m *Dispute) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

func (m *Dispute) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Dispute) GetStatus() DisputeStatus {
	if m != nil {
		return m.Status
	}
	return DisputeStatus_DISPUTE_STATUS_UNSPECIFIED
}

func (m *Dispute) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Dispute) GetEvidence() []Evidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *Dispute) GetVotes() []Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Dispute) GetResult() VoteResult {
	if m != nil {
		return m.Result
	}
	return VoteResult{}
}

func (m *Dispute) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Dispute) GetCompletedAt() int64 {
	if m != nil {
		return m.CompletedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("sharetoken.dispute.DisputeStatus", DisputeStatus_name, DisputeStatus_value)
	proto.RegisterType((*Evidence)(nil), "sharetoken.dispute.Evidence")
	proto.RegisterType((*Vote)(nil), "sharetoken.dispute.Vote")
	proto.RegisterType((*VoteResult)(nil), "sharetoken.dispute.VoteResult")
	proto.RegisterType((*Dispute)(nil), "sharetoken.dispute.Dispute")
}

func init() { proto.RegisterFile("sharetoken/dispute/dispute.proto", fileDescriptor_6b56a149ea2be05a) }

var fileDescriptor_6b56a149ea2be05a = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0xee, 0xb6, 0xa5, 0xb4, 0xa7, 0x50, 0xeb, 0x88, 0xb2, 0x16, 0x5c, 0x0a, 0xc6, 0xd8, 0x78,
	0xd1, 0x06, 0xe4, 0xc6, 0xc4, 0x98, 0x14, 0xba, 0x9a, 0x26, 0x58, 0x48, 0x5b, 0x30, 0xf1, 0x66,
	0xb3, 0xdd, 0x9d, 0xc0, 0xc4, 0xee, 0xce, 0xba, 0x33, 0x05, 0xfb, 0x0a, 0x5e, 0xf9, 0x3a, 0x26,
	0x3c, 0x00, 0x97, 0x5c, 0x7a, 0x65, 0x0c, 0xbc, 0x88, 0x99, 0x9f, 0x5d, 0xa4, 0x62, 0xbc, 0x69,
	0xe7, 0x7c, 0xe7, 0xfb, 0xce, 0x7c, 0x3d, 0xe7, 0x74, 0xa0, 0xce, 0x4e, 0xdc, 0x18, 0x73, 0xfa,
	0x09, 0x87, 0x2d, 0x9f, 0xb0, 0x68, 0xc2, 0x71, 0xf2, 0xdd, 0x8c, 0x62, 0xca, 0x29, 0x42, 0x37,
	0x8c, 0xa6, 0xce, 0xd4, 0xee, 0xbb, 0x01, 0x09, 0x69, 0x4b, 0x7e, 0x2a, 0x5a, 0xcd, 0xf2, 0x28,
	0x0b, 0x28, 0x6b, 0x8d, 0x5c, 0x86, 0x5b, 0xa7, 0x9b, 0x23, 0xcc, 0xdd, 0xcd, 0x96, 0x47, 0x49,
	0xa8, 0xf3, 0x4b, 0xc7, 0xf4, 0x98, 0xca, 0x63, 0x4b, 0x9c, 0x14, 0xba, 0xf1, 0xd5, 0x80, 0xa2,
	0x7d, 0x4a, 0x7c, 0x1c, 0x7a, 0x18, 0xad, 0xc3, 0x02, 0x9b, 0x8c, 0x02, 0xc2, 0x39, 0xf6, 0x9d,
	0xd1, 0xd4, 0x34, 0xea, 0x46, 0xa3, 0xd4, 0x2f, 0xa7, 0xd8, 0xce, 0x14, 0x3d, 0x85, 0x45, 0xac,
	0xe9, 0x0e, 0x9f, 0x46, 0xd8, 0xcc, 0x4a, 0xce, 0x42, 0x02, 0x0e, 0xa7, 0x11, 0x46, 0x26, 0xcc,
	0x7b, 0x34, 0xe4, 0x38, 0xe4, 0x66, 0x4e, 0xa6, 0x93, 0x10, 0xad, 0x42, 0x89, 0x93, 0x00, 0x33,
	0xee, 0x06, 0x91, 0x99, 0xaf, 0x1b, 0x8d, 0x5c, 0xff, 0x06, 0xd8, 0x08, 0x21, 0x7f, 0x44, 0x39,
	0x46, 0x4b, 0x30, 0x77, 0x4a, 0x39, 0x8e, 0xb5, 0x01, 0x15, 0xa0, 0x47, 0x50, 0x38, 0xc3, 0xe4,
	0xf8, 0x84, 0xeb, 0x3b, 0x75, 0x84, 0x6a, 0x50, 0xf4, 0xb1, 0x47, 0x18, 0xa1, 0xa1, 0xbe, 0x2e,
	0x8d, 0xff, 0x73, 0xdf, 0xb9, 0x01, 0x20, 0x2e, 0xec, 0x63, 0x36, 0x19, 0xdf, 0x2e, 0x64, 0xcc,
	0x14, 0x7a, 0x0e, 0xf7, 0x62, 0xfc, 0x79, 0x82, 0x19, 0xc7, 0xb1, 0x23, 0xfc, 0x30, 0xed, 0xa2,
	0x92, 0xc2, 0xa2, 0x12, 0x43, 0xcf, 0xa0, 0x12, 0xc5, 0x54, 0x74, 0x23, 0xe1, 0x29, 0x4f, 0x8b,
	0x09, 0xaa, 0x68, 0x6b, 0x50, 0x66, 0xd1, 0x98, 0x70, 0xcd, 0xc9, 0x4b, 0x0e, 0x48, 0x48, 0x11,
	0xd6, 0x61, 0x81, 0x53, 0xee, 0x8e, 0x1d, 0xfd, 0x9b, 0xe7, 0xd4, 0x2c, 0x24, 0xf6, 0x41, 0x42,
	0x1b, 0xdf, 0x73, 0x30, 0xdf, 0x51, 0x0b, 0x81, 0x2a, 0x90, 0x25, 0xbe, 0x76, 0x9d, 0x25, 0x3e,
	0x5a, 0x81, 0x12, 0x66, 0x5e, 0x4c, 0xcf, 0x1c, 0xe2, 0x6b, 0xa7, 0x45, 0x05, 0x74, 0x7d, 0xd1,
	0x95, 0xd4, 0xb5, 0xb6, 0x77, 0x03, 0x88, 0x36, 0x24, 0x5e, 0xb5, 0xaf, 0x34, 0x46, 0xaf, 0xa0,
	0xc0, 0xb8, 0xcb, 0x27, 0x4c, 0xfa, 0xa9, 0x6c, 0xad, 0x37, 0xff, 0x5e, 0xce, 0xa6, 0xf6, 0x34,
	0x90, 0xc4, 0xbe, 0x16, 0x88, 0xf1, 0xc5, 0xd8, 0x65, 0x34, 0x34, 0x0b, 0x6a, 0x7c, 0x2a, 0x42,
	0x6f, 0xa0, 0x98, 0x2c, 0x8f, 0x39, 0x5f, 0xcf, 0x35, 0xca, 0x5b, 0xab, 0x77, 0x15, 0x4d, 0x96,
	0x74, 0x27, 0x7f, 0xf1, 0x73, 0x2d, 0xd3, 0x4f, 0x35, 0x68, 0x5b, 0x2d, 0x0b, 0x33, 0x8b, 0x52,
	0x6c, 0xde, 0x25, 0x16, 0x2d, 0xd5, 0x42, 0x45, 0x46, 0xaf, 0x85, 0x1b, 0x31, 0x75, 0xb3, 0x54,
	0x37, 0x1a, 0xe5, 0x2d, 0xeb, 0x5f, 0x32, 0xb5, 0x1b, 0x5a, 0xac, 0x35, 0xe8, 0x09, 0x80, 0x17,
	0x63, 0x57, 0xfc, 0x4d, 0x5c, 0x6e, 0x82, 0xda, 0x2b, 0x8d, 0xb4, 0xb9, 0x98, 0x9d, 0x47, 0x83,
	0x68, 0x8c, 0x35, 0xa1, 0x2c, 0x09, 0xe5, 0x14, 0x6b, 0xf3, 0x17, 0xe7, 0x06, 0x2c, 0xde, 0xea,
	0x13, 0xb2, 0xa0, 0xd6, 0xe9, 0x0e, 0x0e, 0x0e, 0x87, 0xb6, 0x33, 0x18, 0xb6, 0x87, 0x87, 0x03,
	0xe7, 0xb0, 0x37, 0x38, 0xb0, 0x77, 0xbb, 0x6f, 0xbb, 0x76, 0xa7, 0x9a, 0x41, 0xcb, 0xf0, 0x60,
	0x26, 0xbf, 0x7f, 0x60, 0xf7, 0xaa, 0x06, 0x5a, 0x05, 0x73, 0x26, 0xf1, 0xde, 0xee, 0x74, 0xdb,
	0xc3, 0x6e, 0xef, 0x5d, 0x35, 0x8b, 0x1e, 0xc3, 0xc3, 0x99, 0xec, 0xd1, 0xbe, 0x4c, 0xe5, 0xd0,
	0x0a, 0x2c, 0xcf, 0xa4, 0xfa, 0xf6, 0x60, 0x7f, 0xef, 0xc8, 0xee, 0x54, 0xf3, 0x77, 0x54, 0xdd,
	0x6d, 0xf7, 0x76, 0xed, 0xbd, 0x3d, 0xbb, 0x53, 0x9d, 0xdb, 0xd9, 0xbe, 0xb8, 0xb2, 0x8c, 0xcb,
	0x2b, 0xcb, 0xf8, 0x75, 0x65, 0x19, 0xdf, 0xae, 0xad, 0xcc, 0xe5, 0xb5, 0x95, 0xf9, 0x71, 0x6d,
	0x65, 0x3e, 0xd6, 0xfe, 0x78, 0xcf, 0xbe, 0xa4, 0x2f, 0x9a, 0x78, 0x2a, 0xd8, 0xa8, 0x20, 0xdf,
	0x9c, 0x97, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x75, 0x84, 0x67, 0xf4, 0x04, 0x00, 0x00,
}

func (m *Evidence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Evidence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Evidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintDispute(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EvidenceType) > 0 {
		i -= len(m.EvidenceType)
		copy(dAtA[i:], m.EvidenceType)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.EvidenceType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SubmittedBy) > 0 {
		i -= len(m.SubmittedBy)
		copy(dAtA[i:], m.SubmittedBy)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.SubmittedBy)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Vote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintDispute(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Decision) > 0 {
		i -= len(m.Decision)
		copy(dAtA[i:], m.Decision)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.Decision)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Weight) > 0 {
		i -= len(m.Weight)
		copy(dAtA[i:], m.Weight)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.Weight)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VoteResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VoteResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VoteResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalWeight) > 0 {
		i -= len(m.TotalWeight)
		copy(dAtA[i:], m.TotalWeight)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.TotalWeight)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SplitVotes) > 0 {
		i -= len(m.SplitVotes)
		copy(dAtA[i:], m.SplitVotes)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.SplitVotes)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ProviderVotes) > 0 {
		i -= len(m.ProviderVotes)
		copy(dAtA[i:], m.ProviderVotes)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.ProviderVotes)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RequesterVotes) > 0 {
		i -= len(m.RequesterVotes)
		copy(dAtA[i:], m.RequesterVotes)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.RequesterVotes)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Decision) > 0 {
		i -= len(m.Decision)
		copy(dAtA[i:], m.Decision)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.Decision)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Dispute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Dispute) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Dispute) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompletedAt != 0 {
		i = encodeVarintDispute(dAtA, i, uint64(m.CompletedAt))
		i--
		dAtA[i] = 0x58
	}
	if m.CreatedAt != 0 {
		i = encodeVarintDispute(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x50
	}
	{
		size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDispute(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Votes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDispute(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Evidence) > 0 {
		for iNdEx := len(m.Evidence) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Evidence[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDispute(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x32
	}
	if m.Status != 0 {
		i = encodeVarintDispute(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EscrowId) > 0 {
		i -= len(m.EscrowId)
		copy(dAtA[i:], m.EscrowId)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.EscrowId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintDispute(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDispute(dAtA []byte, offset int, v uint64) int {
	offset -= sovDispute(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Evidence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubmittedBy)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.EvidenceType)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovDispute(uint64(m.Timestamp))
	}
	return n
}

func (m *Vote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.Weight)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.Decision)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovDispute(uint64(m.Timestamp))
	}
	return n
}

func (m *VoteResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Decision)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.RequesterVotes)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.ProviderVotes)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.SplitVotes)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.TotalWeight)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	return n
}

func (m *Dispute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.EscrowId)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovDispute(uint64(m.Status))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovDispute(uint64(l))
	}
	if len(m.Evidence) > 0 {
		for _, e := range m.Evidence {
			l = e.Size()
			n += 1 + l + sovDispute(uint64(l))
		}
	}
	if len(m.Votes) > 0 {
		for _, e := range m.Votes {
			l = e.Size()
			n += 1 + l + sovDispute(uint64(l))
		}
	}
	l = m.Result.Size()
	n += 1 + l + sovDispute(uint64(l))
	if m.CreatedAt != 0 {
		n += 1 + sovDispute(uint64(m.CreatedAt))
	}
	if m.CompletedAt != 0 {
		n += 1 + sovDispute(uint64(m.CompletedAt))
	}
	return n
}

func sovDispute(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDispute(x uint64) (n int) {
	return sovDispute(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Evidence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Evidence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Evidence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubmittedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Vote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decision", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Decision = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VoteResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VoteResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VoteResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decision", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Decision = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterVotes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterVotes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderVotes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderVotes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SplitVotes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SplitVotes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalWeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalWeight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Dispute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Dispute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Dispute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= DisputeStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Evidence = append(m.Evidence, Evidence{})
			if err := m.Evidence[len(m.Evidence)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, Vote{})
			if err := m.Votes[len(m.Votes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDispute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAt", wireType)
			}
			m.CompletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDispute(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDispute
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDispute
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDispute
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDispute
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDispute
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDispute        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDispute          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDispute = fmt.Errorf("proto: unexpected end of group")
)
