// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sharetoken/identity/identity.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Identity represents a user's on-chain identity
type Identity struct {
	// address is the blockchain address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// did is the Decentralized Identifier
	Did string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	// verification_hash is the hash of verification result (not plaintext)
	VerificationHash string `protobuf:"bytes,3,opt,name=verification_hash,json=verificationHash,proto3" json:"verification_hash,omitempty"`
	// verification_provider is the provider used (wechat/github/google)
	VerificationProvider string `protobuf:"bytes,4,opt,name=verification_provider,json=verificationProvider,proto3" json:"verification_provider,omitempty"`
	// registration_time is the Unix timestamp of registration
	RegistrationTime uint64 `protobuf:"varint,5,opt,name=registration_time,json=registrationTime,proto3" json:"registration_time,omitempty"`
	// is_verified indicates if identity is verified
	IsVerified bool `protobuf:"varint,6,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	// merkle_root is the root hash of the identity merkle tree
	MerkleRoot string `protobuf:"bytes,7,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	// metadata_hash is hash of additional encrypted metadata
	MetadataHash string `protobuf:"bytes,8,opt,name=metadata_hash,json=metadataHash,proto3" json:"metadata_hash,omitempty"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_29e126c8cd081bc8, []int{0}
}
func (m *Identity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return m.Size()
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Identity) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *Identity) GetVerificationHash() string {
	if m != nil {
		return m.VerificationHash
	}
	return ""
}

func (m *Identity) GetVerificationProvider() string {
	if m != nil {
		return m.VerificationProvider
	}
	return ""
}

func (m *Identity) GetRegistrationTime() uint64 {
	if m != nil {
		return m.RegistrationTime
	}
	return 0
}

func (m *Identity) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *Identity) GetMerkleRoot() string {
	if m != nil {
		return m.MerkleRoot
	}
	return ""
}

func (m *Identity) GetMetadataHash() string {
	if m != nil {
		return m.MetadataHash
	}
	return ""
}

func init() {
	proto.RegisterType((*Identity)(nil), "sharetoken.identity.Identity")
}

func init() {
	proto.RegisterFile("sharetoken/identity/identity.proto", fileDescriptor_29e126c8cd081bc8)
}

var fileDescriptor_29e126c8cd081bc8 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x86, 0x29, 0x20, 0x60, 0xd5, 0x04, 0x2a, 0x26, 0x0d, 0x26, 0x2b, 0xc1, 0x0b, 0x89, 0x09,
	0x1c, 0x88, 0x2f, 0xe0, 0x49, 0x6f, 0x66, 0x63, 0x3c, 0x78, 0x21, 0xd5, 0x8e, 0xec, 0x04, 0x77,
	0x4b, 0xda, 0x09, 0x91, 0xb7, 0xf0, 0x41, 0x7c, 0x10, 0x8f, 0x1c, 0x3d, 0x1a, 0x78, 0x11, 0xb3,
	0x2d, 0x2b, 0xeb, 0xa5, 0xf9, 0xfb, 0x7f, 0xff, 0x74, 0x32, 0x1d, 0x3e, 0x70, 0x89, 0xb2, 0x40,
	0x66, 0x0e, 0xd9, 0x18, 0x35, 0x64, 0x84, 0xb4, 0xfa, 0x13, 0xa3, 0x85, 0x35, 0x64, 0xc4, 0xe9,
	0x3e, 0x33, 0x2a, 0x50, 0xaf, 0xa3, 0x52, 0xcc, 0xcc, 0xd8, 0x9f, 0x21, 0xd7, 0xeb, 0xce, 0xcc,
	0xcc, 0x78, 0x39, 0xce, 0x55, 0x70, 0x07, 0x9f, 0x55, 0xde, 0xba, 0xdb, 0x55, 0x09, 0xc9, 0x9b,
	0x4a, 0x6b, 0x0b, 0xce, 0x49, 0xd6, 0x67, 0xc3, 0xc3, 0xb8, 0xb8, 0x8a, 0x36, 0xaf, 0x69, 0xd4,
	0xb2, 0xea, 0xdd, 0x5c, 0x8a, 0x2b, 0xde, 0x59, 0x82, 0xc5, 0x57, 0x7c, 0x51, 0x84, 0x26, 0x9b,
	0x26, 0xca, 0x25, 0xb2, 0xe6, 0x79, 0xbb, 0x0c, 0x6e, 0x95, 0x4b, 0xc4, 0x84, 0x9f, 0xfd, 0x0b,
	0x2f, 0xac, 0x59, 0xa2, 0x06, 0x2b, 0xeb, 0xbe, 0xa0, 0x5b, 0x86, 0xf7, 0x3b, 0x96, 0x77, 0xb0,
	0x30, 0x43, 0x47, 0x36, 0x14, 0x11, 0xa6, 0x20, 0x0f, 0xfa, 0x6c, 0x58, 0x8f, 0xdb, 0x65, 0xf0,
	0x80, 0x29, 0x88, 0x0b, 0x7e, 0x84, 0x6e, 0x1a, 0xde, 0x01, 0x2d, 0x1b, 0x7d, 0x36, 0x6c, 0xc5,
	0x1c, 0xdd, 0xe3, 0xce, 0xc9, 0x03, 0x29, 0xd8, 0xf9, 0x1b, 0x4c, 0xad, 0x31, 0x24, 0x9b, 0xbe,
	0x31, 0x0f, 0x56, 0x6c, 0x0c, 0x89, 0x4b, 0x7e, 0x92, 0x02, 0x29, 0xad, 0x48, 0x85, 0x61, 0x5a,
	0x3e, 0x72, 0x5c, 0x98, 0xf9, 0x20, 0x37, 0xd7, 0x5f, 0x9b, 0x88, 0xad, 0x37, 0x11, 0xfb, 0xd9,
	0x44, 0xec, 0x63, 0x1b, 0x55, 0xd6, 0xdb, 0xa8, 0xf2, 0xbd, 0x8d, 0x2a, 0x4f, 0xe7, 0xa5, 0x55,
	0xbd, 0xef, 0x97, 0x45, 0xab, 0x05, 0xb8, 0xe7, 0x86, 0xff, 0xec, 0xc9, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xae, 0xbb, 0xf5, 0x94, 0xd0, 0x01, 0x00, 0x00,
}

func (m *Identity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Identity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Identity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetadataHash) > 0 {
		i -= len(m.MetadataHash)
		copy(dAtA[i:], m.MetadataHash)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.MetadataHash)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0x3a
	}
	if m.IsVerified {
		i--
		if m.IsVerified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.RegistrationTime != 0 {
		i = encodeVarintIdentity(dAtA, i, uint64(m.RegistrationTime))
		i--
		dAtA[i] = 0x28
	}
	if len(m.VerificationProvider) > 0 {
		i -= len(m.VerificationProvider)
		copy(dAtA[i:], m.VerificationProvider)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.VerificationProvider)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.VerificationHash) > 0 {
		i -= len(m.VerificationHash)
		copy(dAtA[i:], m.VerificationHash)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.VerificationHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIdentity(dAtA []byte, offset int, v uint64) int {
	offset -= sovIdentity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Identity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.VerificationHash)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.VerificationProvider)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	if m.RegistrationTime != 0 {
		n += 1 + sovIdentity(uint64(m.RegistrationTime))
	}
	if m.IsVerified {
		n += 2
	}
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.MetadataHash)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	return n
}

func sovIdentity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIdentity(x uint64) (n int) {
	return sovIdentity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Identity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Identity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Identity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationProvider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationProvider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationTime", wireType)
			}
			m.RegistrationTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsVerified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsVerified = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIdentity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIdentity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIdentity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIdentity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIdentity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIdentity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIdentity = fmt.Errorf("proto: unexpected end of group")
)
