// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sharetoken/oracle/price.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PriceSource represents the source of price data
type PriceSource int32

const (
	PriceSource_PRICE_SOURCE_UNSPECIFIED PriceSource = 0
	PriceSource_PRICE_SOURCE_CHAINLINK   PriceSource = 1
	PriceSource_PRICE_SOURCE_MANUAL      PriceSource = 2
)

var PriceSource_name = map[int32]string{
	0: "PRICE_SOURCE_UNSPECIFIED",
	1: "PRICE_SOURCE_CHAINLINK",
	2: "PRICE_SOURCE_MANUAL",
}

var PriceSource_value = map[string]int32{
	"PRICE_SOURCE_UNSPECIFIED": 0,
	"PRICE_SOURCE_CHAINLINK":   1,
	"PRICE_SOURCE_MANUAL":      2,
}

func (x PriceSource) String() string {
	return proto.EnumName(PriceSource_name, int32(x))
}

func (PriceSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ee0a6132a10fa774, []int{0}
}

// Price represents a price data point
type Price struct {
	// symbol is the price symbol (e.g., "STT/USD")
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// price is the price value
	Price github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=price,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"price"`
	// timestamp is the Unix timestamp
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// source is the price source
	Source PriceSource `protobuf:"varint,4,opt,name=source,proto3,enum=sharetoken.oracle.PriceSource" json:"source,omitempty"`
	// confidence is the confidence level (0-100)
	Confidence int32 `protobuf:"varint,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0a6132a10fa774, []int{0}
}
func (m *Price) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Price.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return m.Size()
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Price) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Price) GetSource() PriceSource {
	if m != nil {
		return m.Source
	}
	return PriceSource_PRICE_SOURCE_UNSPECIFIED
}

func (m *Price) GetConfidence() int32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

// LLMPrice represents LLM API pricing
type LLMPrice struct {
	// provider is the LLM provider (e.g., "openai", "anthropic")
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// model is the model name (e.g., "gpt-4", "claude-3")
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// input_price is the price per 1K input tokens
	InputPrice github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=input_price,json=inputPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"input_price"`
	// output_price is the price per 1K output tokens
	OutputPrice github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=output_price,json=outputPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"output_price"`
	// currency is the currency (e.g., "USD")
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (m *LLMPrice) Reset()         { *m = LLMPrice{} }
func (m *LLMPrice) String() string { return proto.CompactTextString(m) }
func (*LLMPrice) ProtoMessage()    {}
func (*LLMPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0a6132a10fa774, []int{1}
}
func (m *LLMPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LLMPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LLMPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LLMPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LLMPrice.Merge(m, src)
}
func (m *LLMPrice) XXX_Size() int {
	return m.Size()
}
func (m *LLMPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_LLMPrice.DiscardUnknown(m)
}

var xxx_messageInfo_LLMPrice proto.InternalMessageInfo

func (m *LLMPrice) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *LLMPrice) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *LLMPrice) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

// GenesisState defines the oracle module's genesis state
type GenesisState struct {
	// prices is the list of prices
	Prices []Price `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0a6132a10fa774, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetPrices() []Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

func init() {
	proto.RegisterEnum("sharetoken.oracle.PriceSource", PriceSource_name, PriceSource_value)
	proto.RegisterType((*Price)(nil), "sharetoken.oracle.Price")
	proto.RegisterType((*LLMPrice)(nil), "sharetoken.oracle.LLMPrice")
	proto.RegisterType((*GenesisState)(nil), "sharetoken.oracle.GenesisState")
}

func init() { proto.RegisterFile("sharetoken/oracle/price.proto", fileDescriptor_ee0a6132a10fa774) }

var fileDescriptor_ee0a6132a10fa774 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0x36, 0x75, 0xd4, 0x4c, 0x2a, 0x14, 0x96, 0xaa, 0x98, 0xa8, 0xb8, 0x56, 0x0e, 0xc8,
	0x42, 0xc2, 0x56, 0x5b, 0x89, 0x7b, 0xbe, 0x0a, 0x16, 0x69, 0x1a, 0x36, 0xca, 0x85, 0x4b, 0xb0,
	0x37, 0x4b, 0x6a, 0x35, 0xf6, 0x5a, 0xde, 0x75, 0x45, 0xfe, 0x05, 0x3f, 0xab, 0xc7, 0x1e, 0x11,
	0x48, 0x15, 0x4a, 0xfe, 0x06, 0x07, 0x64, 0xaf, 0x49, 0x52, 0x21, 0x2e, 0x3d, 0xd9, 0x33, 0xef,
	0xf9, 0xcd, 0xbc, 0x27, 0x0f, 0xbc, 0x14, 0x57, 0x5e, 0xc2, 0x24, 0xbf, 0x66, 0x91, 0xc3, 0x13,
	0x8f, 0xce, 0x99, 0x13, 0x27, 0x01, 0x65, 0x76, 0x9c, 0x70, 0xc9, 0xf1, 0xd3, 0x0d, 0x6c, 0x2b,
	0xb8, 0x71, 0x30, 0xe3, 0x33, 0x9e, 0xa3, 0x4e, 0xf6, 0xa6, 0x88, 0x0d, 0x83, 0x72, 0x11, 0x72,
	0xe1, 0xf8, 0x9e, 0x60, 0xce, 0xcd, 0x89, 0xcf, 0xa4, 0x77, 0xe2, 0x50, 0x1e, 0x44, 0x0a, 0x6f,
	0xfe, 0x44, 0xa0, 0x0d, 0x33, 0x61, 0x7c, 0x08, 0x15, 0xb1, 0x08, 0x7d, 0x3e, 0xd7, 0x91, 0x89,
	0xac, 0x2a, 0x29, 0x2a, 0xdc, 0x05, 0x2d, 0x9f, 0xac, 0xef, 0x64, 0xed, 0xb6, 0x7d, 0x7b, 0x7f,
	0x5c, 0xfa, 0x71, 0x7f, 0xfc, 0x6a, 0x16, 0xc8, 0xab, 0xd4, 0xb7, 0x29, 0x0f, 0x9d, 0x62, 0x86,
	0x7a, 0xbc, 0x11, 0xd3, 0x6b, 0x47, 0x2e, 0x62, 0x26, 0xec, 0x2e, 0xa3, 0x44, 0x7d, 0x8c, 0x8f,
	0xa0, 0x2a, 0x83, 0x90, 0x09, 0xe9, 0x85, 0xb1, 0x5e, 0x36, 0x91, 0x55, 0x26, 0x9b, 0x06, 0x7e,
	0x0b, 0x15, 0xc1, 0xd3, 0x84, 0x32, 0x7d, 0xd7, 0x44, 0xd6, 0x93, 0x53, 0xc3, 0xfe, 0xc7, 0x9f,
	0x9d, 0x6f, 0x39, 0xca, 0x59, 0xa4, 0x60, 0x63, 0x03, 0x80, 0xf2, 0xe8, 0x4b, 0x30, 0x65, 0x11,
	0x65, 0xba, 0x66, 0x22, 0x4b, 0x23, 0x5b, 0x9d, 0xe6, 0x6f, 0x04, 0x7b, 0xfd, 0xfe, 0x85, 0x32,
	0xd8, 0x80, 0xbd, 0x38, 0xe1, 0x37, 0xc1, 0x94, 0x25, 0x85, 0xc5, 0x75, 0x8d, 0x0f, 0x40, 0x0b,
	0xf9, 0x94, 0xcd, 0x95, 0x49, 0xa2, 0x0a, 0x7c, 0x09, 0xb5, 0x20, 0x8a, 0x53, 0x39, 0x51, 0x01,
	0x94, 0x1f, 0x15, 0x00, 0xe4, 0x12, 0x6a, 0x85, 0x8f, 0xb0, 0xcf, 0x53, 0xb9, 0x51, 0xdc, 0x7d,
	0x94, 0x62, 0x4d, 0x69, 0xac, 0x5d, 0xd1, 0x34, 0x49, 0x58, 0x44, 0x17, 0x79, 0x00, 0x55, 0xb2,
	0xae, 0x9b, 0xe7, 0xb0, 0xff, 0x8e, 0x45, 0x4c, 0x04, 0x62, 0x24, 0x3d, 0xc9, 0xb2, 0x98, 0xf3,
	0xb9, 0x42, 0x47, 0x66, 0xd9, 0xaa, 0x9d, 0xea, 0xff, 0x8b, 0xb9, 0xbd, 0x9b, 0xad, 0x44, 0x0a,
	0xf6, 0xeb, 0xcf, 0x50, 0xdb, 0x4a, 0x1f, 0x1f, 0x81, 0x3e, 0x24, 0x6e, 0xa7, 0x37, 0x19, 0x5d,
	0x8e, 0x49, 0xa7, 0x37, 0x19, 0x0f, 0x46, 0xc3, 0x5e, 0xc7, 0x3d, 0x77, 0x7b, 0xdd, 0x7a, 0x09,
	0x37, 0xe0, 0xf0, 0x01, 0xda, 0x79, 0xdf, 0x72, 0x07, 0x7d, 0x77, 0xf0, 0xa1, 0x8e, 0xf0, 0x73,
	0x78, 0xf6, 0x00, 0xbb, 0x68, 0x0d, 0xc6, 0xad, 0x7e, 0x7d, 0xa7, 0x7d, 0x76, 0xbb, 0x34, 0xd0,
	0xdd, 0xd2, 0x40, 0xbf, 0x96, 0x06, 0xfa, 0xb6, 0x32, 0x4a, 0x77, 0x2b, 0xa3, 0xf4, 0x7d, 0x65,
	0x94, 0x3e, 0xbd, 0xd8, 0x3a, 0x84, 0xaf, 0x7f, 0x4f, 0x21, 0xcf, 0xc2, 0xaf, 0xe4, 0xbf, 0xf0,
	0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x5d, 0xe2, 0x40, 0x2c, 0x03, 0x00, 0x00,
}

func (m *Price) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Price) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Price) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Confidence != 0 {
		i = encodeVarintPrice(dAtA, i, uint64(m.Confidence))
		i--
		dAtA[i] = 0x28
	}
	if m.Source != 0 {
		i = encodeVarintPrice(dAtA, i, uint64(m.Source))
		i--
		dAtA[i] = 0x20
	}
	if m.Timestamp != 0 {
		i = encodeVarintPrice(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPrice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintPrice(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LLMPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LLMPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LLMPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Currency) > 0 {
		i -= len(m.Currency)
		copy(dAtA[i:], m.Currency)
		i = encodeVarintPrice(dAtA, i, uint64(len(m.Currency)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.OutputPrice.Size()
		i -= size
		if _, err := m.OutputPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPrice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.InputPrice.Size()
		i -= size
		if _, err := m.InputPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPrice(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Model) > 0 {
		i -= len(m.Model)
		copy(dAtA[i:], m.Model)
		i = encodeVarintPrice(dAtA, i, uint64(len(m.Model)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintPrice(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Prices) > 0 {
		for iNdEx := len(m.Prices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Prices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPrice(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintPrice(dAtA []byte, offset int, v uint64) int {
	offset -= sovPrice(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Price) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovPrice(uint64(l))
	}
	l = m.Price.Size()
	n += 1 + l + sovPrice(uint64(l))
	if m.Timestamp != 0 {
		n += 1 + sovPrice(uint64(m.Timestamp))
	}
	if m.Source != 0 {
		n += 1 + sovPrice(uint64(m.Source))
	}
	if m.Confidence != 0 {
		n += 1 + sovPrice(uint64(m.Confidence))
	}
	return n
}

func (m *LLMPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovPrice(uint64(l))
	}
	l = len(m.Model)
	if l > 0 {
		n += 1 + l + sovPrice(uint64(l))
	}
	l = m.InputPrice.Size()
	n += 1 + l + sovPrice(uint64(l))
	l = m.OutputPrice.Size()
	n += 1 + l + sovPrice(uint64(l))
	l = len(m.Currency)
	if l > 0 {
		n += 1 + l + sovPrice(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Prices) > 0 {
		for _, e := range m.Prices {
			l = e.Size()
			n += 1 + l + sovPrice(uint64(l))
		}
	}
	return n
}

func sovPrice(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPrice(x uint64) (n int) {
	return sovPrice(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Price) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPrice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Price: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Price: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			m.Source = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Source |= PriceSource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Confidence", wireType)
			}
			m.Confidence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Confidence |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPrice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPrice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LLMPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPrice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LLMPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LLMPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Model = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InputPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OutputPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Currency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPrice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPrice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPrice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPrice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPrice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prices = append(m.Prices, Price{})
			if err := m.Prices[len(m.Prices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPrice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPrice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPrice(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPrice
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPrice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPrice
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPrice
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPrice
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPrice        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPrice          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPrice = fmt.Errorf("proto: unexpected end of group")
)
